package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "og",
		Description: "CAH OG Cards",
		Prompts: []*PromptCard{
&PromptCard{Prompt: `%s - theres an app for that.`},
&PromptCard{Prompt: `Why can't I sleep at night?`},
&PromptCard{Prompt: `What's that smell?`},
&PromptCard{Prompt: `I got 99 problems but %s ain't one.`},
&PromptCard{Prompt: `Maybe she's born with it.  Maybe it's %s.`},
&PromptCard{Prompt: `Whats the next Happy Meal toy?`},
&PromptCard{Prompt: `Anthropologists have recently discovered a primitive tribe that worships %s.`},
&PromptCard{Prompt: `It's a pity that kids these days are all getting involved with %s.`},
&PromptCard{Prompt: `During Picassos often-overlooked Brown Period, he produced hundreds of paintings of %s.`},
&PromptCard{Prompt: `Alternative medicine is now embracing the curative powers of %s.`},
&PromptCard{Prompt: `And the Academy Award for %s goes to %s.`},
&PromptCard{Prompt: `What's that sound?`},
&PromptCard{Prompt: `What ended my last relationship?`},
&PromptCard{Prompt: `MTV's new reality show features eight washed-up celebrities living with %s.`},
&PromptCard{Prompt: `I drink to forget %s.`},
&PromptCard{Prompt: `Im sorry professor, but I couldnt complete my homework because of %s.`},
&PromptCard{Prompt: `What is Batman's guilty pleasure?`},
&PromptCard{Prompt: `This is the way the world ends <br> This is the way the world ends <br> Not with a bang but with %s.`},
&PromptCard{Prompt: `What's a girl's best friend?`},
&PromptCard{Prompt: `TSA guidelines now prohibit %s on airplanes.`},
&PromptCard{Prompt: `%s.  That's how I want to die.`},
&PromptCard{Prompt: `For my next trick, I will pull %s out of %s.`},
&PromptCard{Prompt: `In the new Disney Channel Original Movie, Hannah Montana struggles with %s for the first time.`},
&PromptCard{Prompt: `%s is a slippery slope that leads to %s.`},
&PromptCard{Prompt: `What does Dick Cheney prefer?`},
&PromptCard{Prompt: `Dear Abby, I'm having some trouble with %s and would like your advice.`},
&PromptCard{Prompt: `Instead of coal, Santa now gives the bad children %s.`},
&PromptCard{Prompt: `What's the most emo?`},
&PromptCard{Prompt: `In 1,000 years when paper money is but a distant memory, %s will be our currency.`},
&PromptCard{Prompt: `What's the next superhero/sidekick duo?`},
&PromptCard{Prompt: `In M. Night Shyamalan's new movie, Bruce Willis discovers that %s had really been %s all along.`},
&PromptCard{Prompt: `A romantic, candlelit dinner would be incomplete without %s.`},
&PromptCard{Prompt: `%s.  Becha can't have just one!`},
&PromptCard{Prompt: `White people like %s.`},
&PromptCard{Prompt: `%s.  High five, bro.`},
&PromptCard{Prompt: `Next from J.K. Rowling: Harry Potter and the Chamber of %s.`},
&PromptCard{Prompt: `BILLY MAYS HERE FOR %s.`},
&PromptCard{Prompt: `In a world ravaged by %s, our only solace is %s.`},
&PromptCard{Prompt: `War!  What is it good for?`},
&PromptCard{Prompt: `During sex, I like to think about %s.`},
&PromptCard{Prompt: `What are my parents hiding from me?`},
&PromptCard{Prompt: `What will always get you laid?`},
&PromptCard{Prompt: `In L.A. County Jail, word is you can trade 200 cigarettes for %s.`},
&PromptCard{Prompt: `What did I bring back from Mexico?`},
&PromptCard{Prompt: `What don't you want to find in your Chinese food?`},
&PromptCard{Prompt: `What will I bring back in time to convince people that I am a powerful wizard?`},
&PromptCard{Prompt: `How am I maintaining my relationship status?`},
&PromptCard{Prompt: `%s.  It's a trap!`},
&PromptCard{Prompt: `Coming to Broadway this season, %s: The Musical.`},
&PromptCard{Prompt: `While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on %s.`},
&PromptCard{Prompt: `After the earthquake, Sean Penn brought %s to the people of Haiti.`},
&PromptCard{Prompt: `Next on ESPN2, the World Series of %s.`},
&PromptCard{Prompt: `Step 1: %s.  Step 2: %s.  Step 3: Profit.`},
&PromptCard{Prompt: `Rumor has it that Vladimir Putin's favorite dish is %s stuffed with %s.`},
&PromptCard{Prompt: `But before I kill you, Mr. Bond, I must show you %s.`},
&PromptCard{Prompt: `What gives me uncontrollable gas?`},
&PromptCard{Prompt: `What do old people smell like?`},
&PromptCard{Prompt: `The class field trip was completely ruined by %s.`},
&PromptCard{Prompt: `When Pharaoh remained unmoved, Moses called down a Plague of %s.`},
&PromptCard{Prompt: `What's my secret power?`},
&PromptCard{Prompt: `What's there a ton of in heaven?`},
&PromptCard{Prompt: `What would grandma find disturbing, yet oddly charming?`},
&PromptCard{Prompt: `I never truly understood %s until I encountered %s.`},
&PromptCard{Prompt: `What did the U.S. airdrop to the children of Afghanistan?`},
&PromptCard{Prompt: `What helps Obama unwind?`},
&PromptCard{Prompt: `What did Vin Diesel eat for dinner?`},
&PromptCard{Prompt: `%s: good to the last drop.`},
&PromptCard{Prompt: `Why am I sticky?`},
&PromptCard{Prompt: `What gets better with age?`},
&PromptCard{Prompt: `%s: kid-tested, mother-approved.`},
&PromptCard{Prompt: `What's the crustiest?`},
&PromptCard{Prompt: `What's Teach for America using to inspire inner city students to succeed?`},
&PromptCard{Prompt: `Studies show that lab rats navigate mazes 50% faster after being exposed to %s.`},
&PromptCard{Prompt: `Life for American Indians was forever changed when the White Man introduced them to %s.`},
&PromptCard{Prompt: `Make a haiku.`},
&PromptCard{Prompt: `I do not know with what weapons World War III will be fought, but World War IV will be fought with %s.`},
&PromptCard{Prompt: `Why do I hurt all over?`},
&PromptCard{Prompt: `What am I giving up for Lent?`},
&PromptCard{Prompt: `In Michael Jackson's final moments, he thought about %s.`},
&PromptCard{Prompt: `In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on %s.`},
&PromptCard{Prompt: `When I am President of the United States, I will create the Department of %s.`},
&PromptCard{Prompt: `Lifetime&copy; presents %s, the story of %s.`},
&PromptCard{Prompt: `When I am a billionaire, I shall erect a 50-foot statue to commemorate %s.`},
&PromptCard{Prompt: `When I was tripping on acid, %s turned into %s.`},
&PromptCard{Prompt: `That's right, I killed %s.  How, you ask?  %s.`},
&PromptCard{Prompt: `What's my anti-drug?`},
&PromptCard{Prompt: `%s + %s = %s.`},
&PromptCard{Prompt: `What never fails to liven up the party?`},
&PromptCard{Prompt: `What's the new fad diet?`},
&PromptCard{Prompt: `Major League Baseball has banned %s for giving players an unfair advantage.`},
&PromptCard{Prompt: `My plan for world domination begins with %s.`},
&PromptCard{Prompt: `The CIA now interrogates enemy agents by repeatedly subjecting them to %s.`},
&PromptCard{Prompt: `Dear Sir or Madam, We regret to inform you that the Office of %s has denied your request for %s`},
&PromptCard{Prompt: `In Rome, there are whisperings that the Vatican has a secret room devoted to %s.`},
&PromptCard{Prompt: `Science will never explain %s.`},
&PromptCard{Prompt: `When all else fails, I can always masturbate to %s.`},
&PromptCard{Prompt: `I learned the hard way that you can't cheer up a grieving friend with %s.`},
&PromptCard{Prompt: `In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated %s.`},
&PromptCard{Prompt: `An international tribunal has found %s guilty of %s.`},
&PromptCard{Prompt: `The socialist governments of Scandinavia have declared that access to %s is a basic human right.`},
&PromptCard{Prompt: `In his new self-produced album, Kanye West raps over the sounds of %s.`},
&PromptCard{Prompt: `What's the gift that keeps on giving?`},
&PromptCard{Prompt: `Next season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only %s and his wits.`},
&PromptCard{Prompt: `When I pooped, what came out of my butt?`},
&PromptCard{Prompt: `In the distant future, historians will agree that %s marked the beginning of America's decline.`},
&PromptCard{Prompt: `In a pinch, %s can be a suitable substitute for %s.`},
&PromptCard{Prompt: `What has been making life difficult at the nudist colony?`},
&PromptCard{Prompt: `Michael Bay's new three-hour action epic pits %s against %s.`},
&PromptCard{Prompt: `And I would have gotten away with it, too, if it hadn't been for %s.`},
&PromptCard{Prompt: `What brought the orgy to a grinding halt?`},
&PromptCard{Prompt: `During his midlife crisis, my dad got really into %s.`},
&PromptCard{Prompt: `%s would be woefully incomplete without %s.`},
&PromptCard{Prompt: `My new favorite porn star is Joey &#34;%s&#34; McGee.`},
&PromptCard{Prompt: `Before I run for president, I must destroy all evidence of my involvement with %s.`},
&PromptCard{Prompt: `This is your captain speaking. Fasten your seatbelts and prepare for %s.`},
&PromptCard{Prompt: `In his newest and most difficult stunt, David Blaine must escape from %s.`},
&PromptCard{Prompt: `The Five Stages of Grief: denial, anger, bargaining, %s, and acceptance.`},
&PromptCard{Prompt: `My mom freaked out when she looked at my browser history and found %s.com/%s.`},
&PromptCard{Prompt: `I went from %s to %s, all thanks to %s.`},
&PromptCard{Prompt: `Members of New York's social elite are paying thousands of dollars just to experience %s.`},
&PromptCard{Prompt: `This month's Cosmo: Spice up your sex life by bringing %s into the bedroom.&#34;`},
&PromptCard{Prompt: `Little Miss Muffet Sat on a tuffet, Eating her curds and %s.`},
&PromptCard{Prompt: `If God didn't want us to enjoy %s, he wouldn't have given us %s.`},
&PromptCard{Prompt: `My country, 'tis of thee, sweet land of %s.`},
&PromptCard{Prompt: `After months of debate, the Occupy Wall Street General Assembly could only agree on &#34;More %s!&#34;`},
&PromptCard{Prompt: `I spent my whole life working toward %s, only to have it ruined by %s.`},
&PromptCard{Prompt: `Next time on Dr. Phil: How to talk to your child about %s.`},
&PromptCard{Prompt: `Only two things in life are certain: death and %s.`},
&PromptCard{Prompt: `Everyone down on the ground! We don't want to hurt anyone. We're just here for %s.`},
&PromptCard{Prompt: `The healing process began when I joined a support group for victims of %s.`},
&PromptCard{Prompt: `The votes are in, and the new high school mascot is %s.`},
&PromptCard{Prompt: `Charades was ruined for me forever when my mom had to act out %s.`},
&PromptCard{Prompt: `Before %s, all we had was %s.`},
&PromptCard{Prompt: `Tonight on 20/20: What you don't know about %s could kill you.`},
&PromptCard{Prompt: `You haven't truly lived until you've experienced %s and %s at the same time.`},
&PromptCard{Prompt: `D&D 4.0 isn't real D&D because of the %s.`},
&PromptCard{Prompt: `It's a D&D retroclone with %s added.`},
&PromptCard{Prompt: `Storygames aren't RPGs because of the %s.`},
&PromptCard{Prompt: `The Slayer's Guide to %s.`},
&PromptCard{Prompt: `Worst character concept ever: %s, but with %s.`},
&PromptCard{Prompt: `Alightment: Chaotic %s`},
&PromptCard{Prompt: `It's a D&D retroclone with %s added.`},
&PromptCard{Prompt: `What made the paladin fall? %s`},
&PromptCard{Prompt: `The portal leads to the quasi-elemental plane of %s.`},
&PromptCard{Prompt: `The Temple of Elemental %s.`},
&PromptCard{Prompt: `Pathfinder is basically D&D %s Edition.`},
&PromptCard{Prompt: `%s : The Storytelling Game.`},
&PromptCard{Prompt: `People are wondering why Steve Jackson published GURPS %s.`},
&PromptCard{Prompt: `Linear Fighter, Quadratic %s.`},
&PromptCard{Prompt: `You start with 1d4 %s points.`},
&PromptCard{Prompt: `Back when I was 12 and I was just starting playing D&D, the game had %s.`},
&PromptCard{Prompt: `Big Eyes, Small %s.`},
&PromptCard{Prompt: `In the grim darkness of the future there is only %s.`},
&PromptCard{Prompt: `My innovative new RPG has a stat for %s.`},
&PromptCard{Prompt: `A true gamer has no problem with %s.`},
&PromptCard{Prompt: `Elminster cast a potent %s spell and then had sex with %s.`},
&PromptCard{Prompt: `The Deck of Many %s.`},
&PromptCard{Prompt: `You are all at a tavern when %s approach you.`},
&PromptCard{Prompt: `For the convention I cosplayed as Sailor Moon, except with %s.`},
&PromptCard{Prompt: `The worst part of Grave of the Fireflies is all the %s.`},
&PromptCard{Prompt: `In the Evangelion remake, Shinji has to deal with %s.`},
&PromptCard{Prompt: `Worst anime convention purchase ever? %s.`},
&PromptCard{Prompt: `While powering up Vegeta screamed, %s!`},
&PromptCard{Prompt: `You evaded my %s attack. Most impressive.`},
&PromptCard{Prompt: `I downloaded a doujin where %s got into %s.`},
&PromptCard{Prompt: `The magical girl found out that the Power of Love is useless against %s.`},
&PromptCard{Prompt: `The Japanese government has spent billions of yen researching %s.`},
&PromptCard{Prompt: `In the dubbed version they changed %s into %s.`},
&PromptCard{Prompt: `%s is Best Pony.`},
&PromptCard{Prompt: `The %s of Haruhi Suzumiya.`},
&PromptCard{Prompt: `The new thing in Akihabara is fetish cafes where you can see girls dressed up as %s.`},
&PromptCard{Prompt: `Your drill can pierce %s!`},
&PromptCard{Prompt: `Avatar: The Last %s bender.`},
&PromptCard{Prompt: `In the name of %s Sailor Moon will punish you!`},
&PromptCard{Prompt: `No harem anime is complete without %s.`},
&PromptCard{Prompt: `My boyfriend's a %s now.`},
&PromptCard{Prompt: `The %s of %s has left me in despair!`},
&PromptCard{Prompt: `%s.tumblr.com`},
&PromptCard{Prompt: `Somehow they made a cute mascot girl out of %s.`},
&PromptCard{Prompt: `Haruko hit Naoto in the head with her bass guitar and %s came out.`},
&PromptCard{Prompt: `After blacking out during New year's Eve, I was awoken by %s.`},
&PromptCard{Prompt: `This holiday season, Tim Allen must overcome his fear of %s to save Christmas.`},
&PromptCard{Prompt: `Jesus is %s.`},
&PromptCard{Prompt: `Every Christmas, my uncle gets drunk and tells the story about %s.`},
&PromptCard{Prompt: `What keeps me warm during the cold, cold, winter?`},
&PromptCard{Prompt: `On the third day of Christmas, my true love gave to me: three French hens, two turtle doves, and %s.`},
&PromptCard{Prompt: `Wake up, America. Christmas is under attack by secular liberals and their %s.`},
&PromptCard{Prompt: `We got the third rope, now where's the fourth?`},
&PromptCard{Prompt: `Tonights main event, %s vs. %s.`},
&PromptCard{Prompt: `Tackle, Dropdown, %s.`},
&PromptCard{Prompt: `Christopher Daniels is late on his %s.`},
&PromptCard{Prompt: `Instead of booking %s, they should have booked %s.`},
&PromptCard{Prompt: `Genius is 10% inspiration, 90% %s.`},
&PromptCard{Prompt: `They found %s in the dumpster behind %s.`},
&PromptCard{Prompt: `The best thing I ever got for Christmas was %s.`},
&PromptCard{Prompt: `There's no crying in %s.`},
&PromptCard{Prompt: `Mastodon! Pterodactyl! Triceratops! Sabretooth Tiger! %s!`},
&PromptCard{Prompt: `Don't eat the %s.`},
&PromptCard{Prompt: `He did %s with the %s!?!`},
&PromptCard{Prompt: `SOOOOO hot, want to touch the %s.`},
&PromptCard{Prompt: `Stop looking at me %s!`},
&PromptCard{Prompt: `I'm cuckoo for %s puffs.`},
&PromptCard{Prompt: `Silly rabbit, %s are for kids.`},
&PromptCard{Prompt: `Between love and madness lies %s.`},
&PromptCard{Prompt: `Instead of chess, the Grim Reaper now gambles for your soul with a game of %s.`},
&PromptCard{Prompt: `My father gave his life fighting to protect %s from %s.`},
&PromptCard{Prompt: `Why is my throat sore?`},
&PromptCard{Prompt: `%s sparked a city-wide riot that only ended with %s.`},
&PromptCard{Prompt: `I’m very sorry Mrs. Smith, but Little Billy has tested positive for %s.`},
&PromptCard{Prompt: `Instead of beating them, Chris Brown now does %s to women.`},
&PromptCard{Prompt: `Instead of cutting, trendy young emo girls now engage in %s.`},
&PromptCard{Prompt: `The definition of rock bottom is gambling away %s.`},
&PromptCard{Prompt: `The Mayan prophecies really heralded the coming of %s in 2012.`},
&PromptCard{Prompt: `The next US election will be fought on the key issues of %s against %s.`},
&PromptCard{Prompt: `When I was 10 I wrote to Santa wishing for %s.`},
&PromptCard{Prompt: `Where or How I met my last signifigant other: %s.`},
&PromptCard{Prompt: `%s, Never leave home without it.`},
&PromptCard{Prompt: `%s. This is my fetish.`},
&PromptCard{Prompt: `David Icke's newest conspiracy theory states that %s caused %s.`},
&PromptCard{Prompt: `I did %s so you don't have to!`},
&PromptCard{Prompt: `I need your clothes, your bike, and %s.`},
&PromptCard{Prompt: `In a new Cold War retro movie, the red menace tries to conquer the world through the cunning use of %s.`},
&PromptCard{Prompt: `In college, our lecturer made us write a report comparing %s to %s.`},
&PromptCard{Prompt: `In The Hangover part 3, those four guys have to deal with %s, %s, and %s.`},
&PromptCard{Prompt: `My zombie survival kit includes food, water, and %s.`},
&PromptCard{Prompt: `The way to a man's heart is through %s.`},
&PromptCard{Prompt: `What was the theme of my second wedding?`},
&PromptCard{Prompt: `What's the newest Japanese craze to head West?`},
&PromptCard{Prompt: `Everybody loves %s.`},
&PromptCard{Prompt: `I can only express myself through %s.`},
&PromptCard{Prompt: `My new porn DVD was completely ruined by the inclusion of %s`},
&PromptCard{Prompt: `My three wishes will be for %s, %s, and %s.`},
&PromptCard{Prompt: `The latest horrifying school shooting was inspired by %s.`},
&PromptCard{Prompt: `I got fired because of my not-so-secret obsession over %s.`},
&PromptCard{Prompt: `My new favourite sexual position is %s`},
&PromptCard{Prompt: `A successful job interview begins with a firm handshake and ends with %s.`},
&PromptCard{Prompt: `Lovin' you is easy 'cause you're %s.`},
&PromptCard{Prompt: `My life is ruled by a vicious cycle of %s and %s.`},
&PromptCard{Prompt: `The blind date was going horribly until we discovered our shared interest in %s.`},
&PromptCard{Prompt: `%s. Awesome in theory, kind of a mess in practice.`},
&PromptCard{Prompt: `I'm not like the rest of you. I'm too rich and busy for %s.`},
&PromptCard{Prompt: `In the seventh circle of Hell, sinners must endure %s for all eternity.`},
&PromptCard{Prompt: `%s: Hours of fun. Easy to use. Perfect for %s!`},
&PromptCard{Prompt: `What left this stain on my couch?`},
&PromptCard{Prompt: `Call the law offices of Goldstein & Goldstein, because no one should have to tolerate %s in the workplace.`},
&PromptCard{Prompt: `When you get right down to it, %s is just %s.`},
&PromptCard{Prompt: `Turns out that %s-Man was neither the hero we needed nor wanted.`},
&PromptCard{Prompt: `As part of his daily regimen, Anderson Cooper sets aside 15 minutes for %s.`},
&PromptCard{Prompt: `Money can't buy me love, but it can buy me %s.`},
&PromptCard{Prompt: `With enough time and pressure, %s will turn into %s.`},
&PromptCard{Prompt: `And what did you bring for show and tell?`},
&PromptCard{Prompt: `During high school, I never really fit in until I found %s club.`},
&PromptCard{Prompt: `Hey, baby, come back to my place and I'll show you %s.`},
&PromptCard{Prompt: `After months of practice with %s, I think I'm finally ready for %s.`},
&PromptCard{Prompt: `To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of %s.`},
&PromptCard{Prompt: `Finally! A service that delivers %s right to your door.`},
&PromptCard{Prompt: `My gym teacher got fired for adding %s to the obstacle course.`},
&PromptCard{Prompt: `Having problems with %s? Try %s!`},
&PromptCard{Prompt: `As part of his contract, Prince won't perform without %s in his dressing room.`},
&PromptCard{Prompt: `Listen, son. If you want to get involved with %s, I won't stop you. Just steer clear of %s.`},
&PromptCard{Prompt: `I just met you and this is crazy, but here's %s, so %s maybe`},
&PromptCard{Prompt: `It's only %s if you get caught!`},
&PromptCard{Prompt: `%s: The Next Generation`},
&PromptCard{Prompt: `Terminator 4: %s`},
&PromptCard{Prompt: `Disney presents %s on ice!`},
&PromptCard{Prompt: `%s. The other white meat.`},
&PromptCard{Prompt: `A %s a day keeps the %s away.`},
&PromptCard{Prompt: `I'm sweating like a %s at a %s.`},
&PromptCard{Prompt: `I love the smell of %s in the morning.`},
&PromptCard{Prompt: `You're not gonna believe this, but %s.`},
&PromptCard{Prompt: `%s. All the cool kids are doing it.`},
&PromptCard{Prompt: `So I was %s in my cubicle at work, and suddenly %s!`},
&PromptCard{Prompt: `Baskin Robbins just added a 32nd flavor: %s!`},
&PromptCard{Prompt: `I can drive and %s%s%s%s at the same time.`},
&PromptCard{Prompt: `%s ain't nothin' to fuck wit'!`},	
		},

		Responses: []ResponseCard{			
`Flying sex snakes.`,
`Michelle Obama's arms.`,
`German dungeon porn.`,
`White people.`,
`Getting so angry that you pop a boner.`,
`Tasteful sideboob.`,
`Praying the gay away.`,
`Two midgets shitting into a bucket.`,
`MechaHitler.`,
`Being a motherfucking sorcerer.`,
`A disappointing birthday party.`,
`Puppies!`,
`A windmill full of corpses.`,
`Guys who don't call.`,
`Racially-biased SAT questions.`,
`Dying.`,
`Steven Hawking talking dirty.`,
`Being on fire.`,
`A lifetime of sadness.`,
`An erection that lasts longer than four hours.`,
`AIDS`,
`Same-sex ice dancing.`,
`Glenn Beck catching his scrotum on a curtain hook.`,
`The Rapture.`,
`Pterodactyl eggs.`,
`Crippling debt.`,
`Eugenics.`,
`Exchanging pleasantries.`,
`Dying of dysentery.`,
`Roofies.`,
`Getting naked and watching Nickelodeon.`,
`The forbidden fruit.`,
`Republicans.`,
`The Big Bang.`,
`Anal beads.`,
`Amputees.`,
`Men.`,
`Surprise sex!`,
`Kim Jong-il.`,
`Concealing a boner`,
`Agriculture.`,
`Glenn Beck being harried by a swarm of buzzards.`,
`Making a pouty face.`,
`A salty surprise.`,
`The Jews.`,
`Charisma.`,
`YOU MUST CONSTRUCT ADDITIONAL PYLONS.`,
`Panda sex.`,
`Taking off your shirt.`,
`A drive-by shooting.`,
`Ronald Reagan.`,
`Morgan Freeman's voice.`,
`Breaking out into song and dance.`,
`Jewish fraternities.`,
`Dead babies.`,
`Masturbation.`,
`Hormone injections.`,
`All-you-can-eat shrimp for $4.99.`,
`Incest.`,
`Scalping.`,
`Soup that is too hot.`,
`The &Uuml;bermensch.`,
`Nazis.`,
`Tom Cruise.`,
`Stifling a giggle at the mention of Hutus and Tutsis.`,
`Edible underpants.`,
`The Hustle.`,
`A Super Soaker&trade; full of cat pee.`,
`Figgy pudding.`,
`Object permanence.`,
`Consultants.`,
`Intelligent design.`,
`Nocturnal emissions.`,
`Uppercuts.`,
`Being marginalized.`,
`The profoundly handicapped.`,
`Obesity.`,
`Chutzpah.`,
`Unfathomable stupidity.`,
`Repression.`,
`Attitude.`,
`Passable transvestites.`,
`Party poopers.`,
`The American Dream`,
`Child beauty pageants.`,
`Puberty.`,
`Testicular torsion.`,
`The folly of man.`,
`Nickelback.`,
`Swooping.`,
`Goats eating cans.`,
`The KKK.`,
`Kamikaze pilots.`,
`Horrifying laser hair removal accidents.`,
`Adderall&trade;.`,
`A look-see.`,
`Doing the right thing.`,
`The taint; the grundle; the fleshy fun-bridge.`,
`Lactation.`,
`Pabst Blue Ribbon.`,
`Powerful thighs.`,
`Saxophone solos.`,
`The gays.`,
`A middle-aged man on roller skates.`,
`A foul mouth.`,
`The thing that electrocutes your abs.`,
`Heteronormativity.`,
`Cuddling.`,
`Coat hanger abortions.`,
`A big hoopla about nothing.`,
`Boogers.`,
`A hot mess.`,
`Raptor attacks.`,
`My collection of high-tech sex toys.`,
`Fear itself.`,
`<i>Bees?</i>`,
`Getting drunk on mouthwash.`,
`Sniffing glue.`,
`Oversized lollipops.`,
`An icepick lobotomy.`,
`Being rich.`,
`Friends with benefits.`,
`Teaching a robot to love.`,
`Women's suffrage.`,
`Me time.`,
`The heart of a child.`,
`Smallpox blankets.`,
`The clitoris.`,
`John Wilkes Booth.`,
`The glass ceiling.`,
`Sarah Palin.`,
`Sexy pillow fights.`,
`Yeast.`,
`Full frontal nudity.`,
`Parting the Red Sea.`,
`A Bop It&trade;.`,
`Michael Jackson.`,
`Team-building exercises.`,
`Harry Potter erotica.`,
`Authentic Mexican cuisine.`,
`Frolicking.`,
`Sexting.`,
`Grandma.`,
`Not giving a shit about the Third World.`,
`Licking things to claim them as your own.`,
`Genghis Khan.`,
`The hardworking Mexican.`,
`RoboCop.`,
`My relationship status.`,
`Scrubbing under the folds.`,
`Porn Stars.`,
`Horse meat.`,
`Sunshine and rainbows.`,
`Expecting a burp and vomiting on the floor.`,
`Barack Obama.`,
`Spontaneous human combustion.`,
`Natural selection.`,
`Mouth herpes.`,
`Flash flooding.`,
`Goblins.`,
`A monkey smoking a cigar.`,
`Spectacular abs.`,
`A good sniff.`,
`Wiping her butt.`,
`The Three-Fifths compromise.`,
`Pedophiles.`,
`Doin' it in the butt.`,
`Being fabulous.`,
`Mathletes.`,
`Wearing underwear inside-out to avoid doing laundry.`,
`Nipple blades.`,
`An M. Night Shyamalan plot twist.`,
`A bag of magic beans.`,
`Vigorous jazz hands.`,
`A defective condom.`,
`Skeletor.`,
`Vikings.`,
`Leaving an awkward voicemail.`,
`Teenage pregnancy.`,
`Dead parents.`,
`Hot cheese.`,
`My sex life.`,
`A mopey zoo lion.`,
`Assless chaps.`,
`Riding off into the sunset.`,
`Lance Armstrong's missing testicle.`,
`Sweet, sweet vengeance.`,
`Genital piercings.`,
`Keg stands.`,
`Darth Vader.`,
`Viagra&copy;.`,
`Necrophilia.`,
`A really cool hat.`,
`Toni Morrison's vagina.`,
`An Oedipus complex.`,
`The Tempur-Pedic&copy; Swedish Sleep System&trade;.`,
`Preteens.`,
`Dick fingers.`,
`A cooler full of organs.`,
`Shapeshifters.`,
`The Care Bear Stare.`,
`Erectile dysfunction.`,
`Keanu Reeves.`,
`The Virginia Tech Massacre.`,
`The Underground Railroad.`,
`The chronic.`,
`Queefing.`,
`Heartwarming orphans.`,
`A thermonuclear detonation.`,
`Cheating in the Special Olympics.`,
`Tangled Slinkys.`,
`A moment of silence.`,
`Civilian casualties.`,
`Catapults.`,
`Sharing needles.`,
`Ethnic cleansing.`,
`Emotions.`,
`Children on leashes.`,
`Balls.`,
`Homeless people.`,
`Eating all of the cookies before the AIDS bake-sale.`,
`Old-people smell.`,
`Farting and walking away.`,
`The inevitable heat death of the universe.`,
`The violation of our most basic human rights.`,
`Fingering.`,
`The placenta.`,
`The Rev. Dr. Martin Luther King, Jr.`,
`Leprosy.`,
`Sperm whales.`,
`Multiple stab wounds.`,
`Flightless birds.`,
`Grave robbing.`,
`Home video of Oprah sobbing into a Lean Cuisine&copy;.`,
`Oompa-Loompas.`,
`A murder most foul.`,
`Tentacle porn.`,
`Daddy issues.`,
`Bill Nye the Science Guy.`,
`Peeing a little bit.`,
`The miracle of childbirth.`,
`Tweeting.`,
`Another goddamn vampire movie.`,
`Britney Spears at 55.`,
`New Age music.`,
`The Make-A-Wish&reg; Foundation.`,
`Firing a rifle into the air while balls deep in a squealing hog.`,
`Active listening.`,
`Nicolas Cage.`,
`72 virgins.`,
`Stranger danger.`,
`Hope.`,
`A gassy antelope.`,
`BATMAN!!!`,
`Chivalry.`,
`Passing a kidney stone.`,
`Black people.`,
`Natalie Portman.`,
`A mime having a stroke.`,
`Classist undertones.`,
`Sean Penn.`,
`A mating display.`,
`The Holy Bible.`,
`Hot Pockets&copy;.`,
`A sad handjob.`,
`Pulling out.`,
`Serfdom.`,
`Pixelated bukkake.`,
`Dropping a chandelier on your enemies and riding the rope up.`,
`Jew-fros.`,
`Waiting 'til marriage.`,
`Euphoria&trade; by Calvin Klein.`,
`The World of Warcraft.`,
`Lunchables&trade;.`,
`The Kool-Aid Man.`,
`The Trail of Tears.`,
`Self-loathing.`,
`A falcon with a cap on its head.`,
`Historically black colleges.`,
`Not reciprocating oral sex.`,
`Global warming.`,
`Ghosts.`,
`World peace.`,
`A can of whoop-ass.`,
`The Dance of the Sugar Plum Fairy.`,
`A zesty breakfast burrito.`,
`Switching to Geico&reg;.`,
`Aaron Burr.`,
`Picking up girls at the abortion clinic.`,
`Land mines.`,
`Former President George W. Bush.`,
`Geese.`,
`Mutually-assured destruction.`,
`College.`,
`Date rape.`,
`Bling.`,
`A gentle caress of the inner thigh.`,
`A time travel paradox.`,
`Seppuku.`,
`Poor life choices.`,
`Waking up half-naked in a Denny's parking lot.`,
`Italians.`,
`GoGurt&reg;.`,
`Finger painting.`,
`Robert Downey, Jr.`,
`My soul.`,
`Smegma.`,
`Embryonic stem cells.`,
`The South.`,
`Christopher Walken.`,
`Gloryholes.`,
`Pretending to care.`,
`Public ridicule.`,
`A tiny horse.`,
`Arnold Schwarzenegger.`,
`A stray pube.`,
`Jerking off into a pool of children's tears.`,
`Child abuse.`,
`Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.`,
`Menstruation.`,
`A sassy black woman.`,
`Re-gifting.`,
`Penis envy.`,
`A sausage festival.`,
`Getting really high.`,
`Drinking alone.`,
`Too much hair gel.`,
`Hulk Hogan.`,
`Overcompensation.`,
`Foreskin.`,
`Free samples.`,
`Shaquille O'Neal's acting career.`,
`Five-Dollar Footlongs&trade;.`,
`Whipping it out.`,
`A snapping turtle biting the tip of your penis.`,
`Muhammad (Praise Be Unto Him).`,
`Half-assed foreplay.`,
`Dental dams.`,
`Being a dick to children.`,
`Famine.`,
`Chainsaws for hands.`,
`A gypsy curse.`,
`AXE Body Spray.`,
`The Force.`,
`Explosions.`,
`Cybernetic enhancements.`,
`Customer service representatives.`,
`White privilege.`,
`Gandhi.`,
`Road head.`,
`God.`,
`Poorly-timed Holocaust jokes.`,
`8 oz. of sweet Mexican black-tar heroin.`,
`Judge Judy.`,
`The Little Engine That Could.`,
`Altar boys.`,
`Mr. Clean, right behind you.`,
`Vehicular manslaughter.`,
`Dwarf tossing.`,
`Friction.`,
`Lady Gaga.`,
`Scientology.`,
`Justin Bieber.`,
`A death ray.`,
`Vigilante justice.`,
`The Pope.`,
`A sea of troubles.`,
`Alcoholism.`,
`Poor people.`,
`A fetus.`,
`Women in yogurt commercials.`,
`Exactly what you'd expect.`,
`Flesh-eating bacteria.`,
`My genitals.`,
`A balanced breakfast.`,
`Dick Cheney.`,
`Lockjaw.`,
`Natural male enhancement.`,
`Take-backsies.`,
`Winking at old people.`,
`Opposable thumbs.`,
`Flying sex snakes.`,
`Passive-aggressive Post-it notes.`,
`Inappropriate yodeling.`,
`Golden showers.`,
`Racism.`,
`Copping a feel.`,
`Auschwitz.`,
`Elderly Japanese men.`,
`Raping and pillaging.`,
`Kids with ass cancer.`,
`Pictures of boobs.`,
`The homosexual agenda.`,
`A homoerotic volleyball montage.`,
`Sexual tension.`,
`Hurricane Katrina.`,
`Fiery poops.`,
`Science.`,
`Dry heaving.`,
`Cards Against Humanity.`,
`Fancy Feast&copy;.`,
`A bleached asshole.`,
`Lumberjack fantasies.`,
`American Gladiators.`,
`Autocannibalism.`,
`Sean Connery.`,
`William Shatner.`,
`Domino's&trade; Oreo&trade; Dessert Pizza.`,
`An asymmetric boob job.`,
`Centaurs.`,
`A micropenis.`,
`Asians who aren't good at math.`,
`The milk man.`,
`Waterboarding.`,
`Wifely duties.`,
`Loose lips.`,
`The Blood of Christ.`,
`Actually taking candy from a baby.`,
`The token minority.`,
`Jibber-jabber.`,
`A brain tumor.`,
`Bingeing and purging.`,
`A clandestine butt scratch.`,
`The Chinese gymnastics team.`,
`Prancing.`,
`The Hamburglar.`,
`Police brutality.`,
`Man meat.`,
`Forgetting the Alamo.`,
`Eating the last known bison.`,
`Crystal meth.`,
`Booby-trapping the house to foil burglars.`,
`My inner demons.`,
`Third base.`,
`Soiling oneself.`,
`Laying an egg.`,
`Giving 110%.`,
`Hot people.`,
`Friendly fire.`,
`Count Chocula.`,
`Pac-Man uncontrollably guzzling cum.`,
`Estrogen.`,
`My vagina.`,
`Kanye West.`,
`A robust mongoloid.`,
`The Donald Trump Seal of Approval&trade;.`,
`The true meaning of Christmas.`,
`Her Royal Highness, Queen Elizabeth II.`,
`An honest cop with nothing left to lose.`,
`Feeding Rosie O'Donnell.`,
`The Amish.`,
`The terrorists.`,
`When you fart and a little bit comes out.`,
`Pooping back and forth. Forever.`,
`Friends who eat all the snacks.`,
`Cockfights.`,
`Bitches.`,
`Seduction.`,
`A big black dick.`,
`A beached whale.`,
`A bloody pacifier.`,
`A crappy little hand.`,
`A low standard of living.`,
`A nuanced critique.`,
`Panty raids.`,
`A passionate Latino lover.`,
`A rival dojo.`,
`A web of lies.`,
`A woman scorned.`,
`Clams.`,
`Apologizing.`,
`A plunger to the face.`,
`Neil Patrick Harris.`,
`Beating your wives.`,
`Being a dinosaur.`,
`Shaft.`,
`Bosnian chicken farmers.`,
`Nubile slave boys.`,
`Carnies.`,
`Coughing into a vagina.`,
`Suicidal thoughts.`,
`The ooze.`,
`Deflowering the princess.`,
`Dorito breath.`,
`Eating an albino.`,
`Enormous Scandinavian women.`,
`Fabricating statistics.`,
`Finding a skeleton.`,
`Gandalf.`,
`Genetically engineered super-soldiers.`,
`George Clooney's musk.`,
`Getting abducted by Peter Pan.`,
`Getting in her pants, politely.`,
`Gladiatorial combat.`,
`Clenched butt cheeks.`,
`Hipsters.`,
`Historical revisionism.`,
`Insatiable bloodlust.`,
`Jafar.`,
`Jean-Claude Van Damme.`,
`Just the tip.`,
`Mad hacky-sack skills.`,
`Leveling up.`,
`Literally eating shit.`,
`Making the penises kiss.`,
`24-hour media coverage.`,
`Medieval Times&copy; Dinner & Tournament.`,
`Moral ambiguity.`,
`My machete.`,
`One thousand Slim Jims.`,
`Ominous background music.`,
`Overpowering your father.`,
`Stockholm Syndrome.`,
`Quiche.`,
`Quivering jowls.`,
`Revenge fucking.`,
`Ripping into a man's chest and pulling out his still-beating heart.`,
`Ryan Gosling riding in on a white horse.`,
`Santa Claus.`,
`Scrotum tickling.`,
`Sexual humiliation.`,
`Sexy Siamese twins.`,
`Saliva.`,
`Space muffins.`,
`Statistically validated stereotypes.`,
`Sudden Poop Explosion Disease.`,
`The boners of the elderly.`,
`The economy.`,
`Syphilitic insanity.`,
`The Gulags.`,
`The harsh light of day.`,
`The hiccups.`,
`The shambling corpse of Larry King.`,
`The four arms of Vishnu.`,
`Being a busy adult with many important things to do.`,
`Tripping balls.`,
`Words, words, words.`,
`Zeus's sexual appetites.`,
`A bigger, blacker dick.`,
`The mere concept of Applebee's&reg;.`,
`A sad fat dragon with no friends.`,
`Catastrophic urethral trauma.`,
`Hillary Clinton's death stare.`,
`Existing.`,
`A pinata full of scorpions.`,
`Mooing.`,
`Swiftly achieving orgasm.`,
`Daddy's belt.`,
`Double penetration.`,
`Weapons-grade plutonium.`,
`Some really fucked-up shit.`,
`Subduing a grizzly bear and making her your wife.`,
`Rising from the grave.`,
`The mixing of the races.`,
`Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.`,
`Scrotal frostbite.`,
`All of this blood.`,
`Loki, the trickster god.`,
`Whining like a little bitch.`,
`Pumping out a baby every nine months.`,
`Tongue.`,
`Finding Waldo.`,
`Upgrading homeless people to mobile hotspots.`,
`Wearing an octopus for a hat.`,
`An unhinged ferris wheel rolling toward the sea.`,
`Living in a trashcan.`,
`The corporations.`,
`A magic hippie love cloud.`,
`Fuck Mountain.`,
`Survivor's guilt.`,
`Me.`,
`Getting hilariously gang-banged by the Blue Man Group.`,
`Jeff Goldblum.`,
`Making a friend.`,
`A soulful rendition of &#34;Ol' Man River.&#34;`,
`Intimacy problems.`,
`A sweaty, panting leather daddy.`,
`Spring break!`,
`Being awesome at sex.`,
`Dining with cardboard cutouts of the cast of &#34;Friends.&#34;`,
`Another shot of morphine.`,
`Beefin' over turf.`,
`A squadron of moles wearing aviator goggles.`,
`Bullshit.`,
`The Google.`,
`Pretty Pretty Princess Dress-Up Board Game&#174;.`,
`The new Radiohead album.`,
`An army of skeletons.`,
`A man in yoga pants with a ponytail and feather earrings.`,
`Mild autism.`,
`Nunchuck moves.`,
`Whipping a disobedient slave.`,
`An ether-soaked rag.`,
`A sweet spaceship.`,
`A 55-gallon drum of lube.`,
`Special musical guest, Cher.`,
`The human body.`,
`Boris the Soviet Love Hammer.`,
`The grey nutrient broth that sustains Mitt Romney.`,
`Tiny nipples.`,
`Power.`,
`Oncoming traffic.`,
`A dollop of sour cream.`,
`A slightly shittier parallel universe.`,
`My first kill.`,
`Graphic violence, adult language, and some sexual content.`,
`Fetal alcohol syndrome.`,
`The day the birds attacked.`,
`One Ring to rule them all.`,
`Grandpa's ashes.`,
`Basic human decency.`,
`A Burmese tiger pit.`,
`Death by Steven Seagal`,
`Dragon boobs.`,
`Verisimilitude.`,
`Dissociated mechanics.`,
`Rape.`,
`Storygames.`,
`Random chargen`,
`RPG.net.`,
`Dice inserted somewhere painful.`,
`FATAL.`,
`Ron Edwards' brain damage.`,
`Boob plate armor.`,
`Gamer chicks.`,
`GNS theory.`,
`Drizzt.`,
`The entire Palladium Books&reg; Megaverse&trade;`,
`BadWrongFun.`,
`Misogynerds.`,
`Cultural Marxism.`,
`Pissing on Gary Gygax's grave.`,
`Steve Jackson's beard.`,
`Natural 20.`,
`Rapenards.`,
`The Crisis of Treachery&trade;.`,
`Game balance.`,
`Fishmalks.`,
`A kick to the dicebags.`,
`Bearded dwarven women.`,
`Owlbear's tears.`,
`Magic missile.`,
`THAC0.`,
`Bigby's Groping Hands.`,
`Drow blackface.`,
`Save or die.`,
`Swine.`,
`The Forge.`,
`Healing Surges.`,
`Gelatinous Cubes.`,
`Total Party Kill.`,
`Quoting Monty Python.`,
`Dumbed down shit for ADD WoW babies.`,
`Mike Mearls.`,
`Comeliness.`,
`Vampire: The Masquerade.`,
`Rifts&trade;.`,
`The random prostitute table.`,
`Dildo of Enlightenment +2`,
`Grognards Against Humanity.`,
`Cthulhu.`,
`The naked succubus in the Monster Manual.`,
`Role-playing and roll-playing.`,
`Fun Tyrant.`,
`4rries.`,
`Martial dailies.`,
`Black Tokyo.`,
`Killfuck Soulshitter.`,
`Cheetoism.`,
`Grimdark.`,
`Kobolds.`,
`Oozemaster.`,
`Rocks fall, everyone dies.`,
`Mark Rein&middot;Hagen.`,
`Maid RPG.`,
`Splugorth blind warrior women.`,
`Dying during chargen.`,
`Slaughtering innocent orc children.`,
`Lesbian stripper ninjas.`,
`Magical tea party.`,
`Grinding levels.`,
`Dice animism.`,
`White privilege.`,
`Githyanki therapy.`,
`Amber Diceless Roleplaying.`,
`A ratcatcher with a small but vicious dog.`,
`Bribing the GM with sexual favors.`,
`Eurocentric fantasy.`,
`Sacred cows.`,
`Gygaxian naturalism.`,
`Special snowflakes.`,
`Neckbeards.`,
`Gazebos.`,
`Lorraine Williams.`,
`Nude larping.`,
`Portable holes.`,
`Steampunk bullshit.`,
`Dump stats.`,
`Ale and whores.`,
`Japanese schoolgirl porn.`,
`Horny catgirls.`,
`Japanese people.`,
`Cimo.`,
`ZA WARUDO!`,
`40 gigs of lolicon.`,
`Goku's hair.`,
`Slashfic.`,
`Star Gentle Uterus`,
`Naruto headbands.`,
`Homestuck troll horns.`,
`Hayao Miyazaki.`,
`The tsunami.`,
`Death Note.`,
`Small breasts.`,
`Asians being racist against each other.`,
`Weeaboo bullshit.`,
`Tsundere.`,
`Body pillows.`,
`A lifelike silicone love doll.`,
`Anime figures drenched in jizz.`,
`Surprise sex.`,
`Yaoi.`,
`Girls with glasses.`,
`Bronies.`,
`Blue and white striped panties.`,
`4chan.`,
`Hello Kitty vibrator.`,
`Finishing attack.`,
`Keikaku* *(keikaku means plan).`,
`Hatsune Miku's screams.`,
`School swimsuits.`,
`Lovingly animated bouncing boobs.`,
`Dragon Balls.`,
`Zangief's chest hair.`,
`DeviantArt.`,
`Giant fucking robots.`,
`Crossplay.`,
`Moeblob.`,
`Carl Macek's rotting corpse.`,
`My waifu.`,
`Voice actress Megumi Hayashibara.`,
`Lynn Minmei.`,
`Panty shots.`,
`Love and Justice.`,
`Consensual tentacle rape.`,
`Gundam.`,
`Captain Bright slapping Amuro.`,
`The Wave Undulation Cannon.`,
`Having sex in the P.E. equipment shed.`,
`Tainted sushi.`,
`Shitty eurobeat music.`,
`Bad dubbing.`,
`Fangirls.`,
`Kawaii desu uguu.`,
`Futanari.`,
`Lesbian schoolgirls.`,
`Osamu Tezuka, rolling in his grave forever.`,
`FUNimation.`,
`Underage cosplayers in bondage gear.`,
`Jackie Chan.`,
`Exchanging Pocky for sexual favors.`,
`Shipping.`,
`Chiyo's father.`,
`Magikarp.`,
`Derpy.`,
`Nanoha and her special friend Fate.`,
`The marbles from Ramune bottles.`,
`Wideface.`,
`Spoilers.`,
`Man-Faye.`,
`Oppai mousepads.`,
`Another dimension.`,
`Homura sniffing Madoka's panties.`,
`Hadouken.`,
`Asian ball-jointed dolls.`,
`J-list.`,
`Childhood friends.`,
`Monkey D. Luffy's rubbery cock.`,
`Cloud's giant fucking Buster Swords.`,
`Taking a dump in Char's helmet.`,
`Hentai marathons.`,
`Gothic Lolita.`,
`Onaholes.`,
`Super Saiyan Level 2.`,
`Gaia Online.`,
`Santa's heavy sack.`,
`Clearing a bloody path through Walmart with a scimitar.`,
`Another shitty year.`,
`Whatever Kwanzaa is supposed to be about.`,
`A Christmas stocking full of coleslaw.`,
`Elf cum.`,
`The tiny, calloused hands of the Chinese children that made this card.`,
`Taking down Santa with a surface-to-air missile.`,
`Socks.`,
`Pretending to be happy.`,
`Krampus, the Austrian Christmas monster.`,
`The Star Wars Holiday Special.`,
`My hot cousin.`,
`Mall Santa.`,
`Several intertwining love stories featuring Hugh Grant.`,
`A Hungry-Man&trade; Frozen Christmas Dinner for one.`,
`Gift-wrapping a live hamster.`,
`Space Jam on VHS.`,
`Immaculate conception.`,
`Fucking up 'Silent Night' in front of 300 parents.`,
`A visually arresting turtleneck.`,
`A toxic family environment.`,
`Eating an entire snowman.`,
`Bumpses.`,
`A Vin Gerard H8 X 10.`,
`Harry Acropolis.`,
`Under the ring.`,
`Afa The Wild Samoan.`,
`Peanut Butter and Baby sandwiches.`,
`Yard Tards.`,
`Two girls, one cup.`,
`Ugly Mexican Hookers.`,
`Duct tape.`,
`Sodaj.`,
`Steve The Teacher.`,
`Jefferee.`,
`Autoerotic Asphyxiation.`,
`Sonic The Hedgehog.`,
`Lotto Money.`,
`Jailbait.`,
`Prison rape.`,
`Two And A Half Men.`,
`Anne Frank.`,
`Black Santa.`,
`Jesus Christ (our lord and saviour).`,
`Farting with your armpits.`,
`Poopsicles.`,
`Slaughtering innocent children.`,
`Sex with vegetables.`,
`My gay ex-husband.`,
`Accidentally sexting your mom.`,
`Tabasco in your pee-hole.`,
`Pee Wee Herman.`,
`A breath of fresh air.`,
`A great big floppy donkey dick.`,
`A pyramid scheme.`,
`A school bus surrounded by cop cars.`,
`A short walk in the desert with shovels.`,
`All the boys staring at your chest.`,
`An amorous stallion.`,
`Being so wet it just slides out of you.`,
`Being tarred and feathered.`,
`Catching 'em all.`,
`Chained to the bed and whipped to orgasmic bliss by a leather-clad woman.`,
`Child-bearing hips.`,
`Defenestration.`,
`Dungeons and/or dragons.`,
`Ecco the Dolphin.`,
`George Washington riding on a giant eagle.`,
`Getting abducted and probed by aliens.`,
`Going viral on YouTube.`,
`Gushing.`,
`Making the baby Jesus cry.`,
`More than you can chew.`,
`Napalm.`,
`Pancake bitches.`,
`Playing God with the power of lightning.`,
`Playing tonsil-hockey.`,
`Racing cheese wheels downhill.`,
`Riding the bomb.`,
`Settling arguments with dance-offs.`,
`Sheer spite.`,
`Sinister laughter.`,
`SS Girls.`,
`Stealing your sister's underwear.`,
`Stroking a cat the wrong way.`,
`Sucking and blowing.`,
`The bullet with your name on it.`,
`The entire rest of eternity, spent in fucking Bruges.`,
`The oceans rising to reclaim the land.`,
`A cocained-fuelled sex orgy heart attack.`,
`A cocktail umbrella `,
`A murder/suicide pact.`,
`A squirming mass of kittens.`,
`An angry mob with torches and pitchforks.`,
`Biting my girlfriend like a vampire during sex.`,
`Dropping your pants and saluting.`,
`Frankenstein's Monster`,
`Getting a blowjob in a theater.`,
`Going full retard.`,
`Going slob-slob-slob all over that knob.`,
`Leaking implants.`,
`Low-flying planes.`,
`Monkies flinging their own shit.`,
`My robot duplicate.`,
`Other people’s children.`,
`People who can't take a joke. Seriously.`,
`Popping a boner during Sex Ed class.`,
`Projectile vomiting.`,
`Pulling down panties with your teeth.`,
`Saying `,
`Shedding skin like a snake.`,
`Shooting Valley Girls for like, saying like all the time. Really.`,
`Slow seductive tentacle rape.`,
`Talking like a pirate, y’arr!`,
`Tenderly kissing a unicorn's horn.`,
`That bastard Jesus!`,
`The last shreads of dignity.`,
`The power of friendship.`,
`This card intentionally left blank.`,
`Throwing water on a braless woman in a white t-shirt`,
`Upskirts.`,
`Wasting all your money on hookers and booze.`,
`Winning.`,
`A foot fetish.`,
`A powerful gag reflex.`,
`A tight, Asian pussy.`,
`Explosive decompression.`,
`Extraordinary Rendition.`,
`Forgetting the safety word.`,
`Greeting Christmas carollers naked.`,
`Handcuffs, without the key.`,
`Having a drill for a penis.`,
`Hot Jailbait Ass.`,
`Liposuction gone horrible wrong.`,
`My harem of scantily clad women.`,
`Nazi Zombie Robot Ninjas.`,
`Redneck gypsies.`,
`Scissoring.`,
`A guy and two robots who won’t shut up.`,
`A shotgun wedding.`,
`Anne Frank's diary`,
`Autoerotic asphyxiation.`,
`Blow Up Bianca the Latex Lovedoll.`,
`Endlessly tumbling down an up escalator.`,
`Fun with nuns.`,
`Getting it all over the walls.`,
`Holiday Dinner by Jack Daniels.`,
`Nailgun fights.`,
`Teaching the bitch a lesson.`,
`Nazi super science.`,
`Making a human centipede.`,
`The primal, ball-slapping sex your parents are having right now.`,
`A cat video so cute that your eyes roll back and your spine slides out of your anus.`,
`Cock.`,
`A cop who is also a dog.`,
`Dying alone and in pain.`,
`Gay aliens.`,
`The way white people is.`,
`Reverse cowgirl.`,
`The Quesadilla Explosion Salad&trade; from Chili's&copy;.`,
`Actually getting shot, for real.`,
`Not having sex.`,
`Vietnam flashbacks.`,
`Running naked through a mall, pissing and shitting everywhere.`,
`Nothing.`,
`Warm, velvety muppet sex.`,
`Self-flagellation.`,
`The systematic destruction of an entire people and their way of life.`,
`Samuel L. Jackson.`,
`A boo-boo.`,
`Going around punching people.`,
`The entire Internet.`,
`Some kind of bird-man.`,
`Chugging a lava lamp.`,
`Having sex on top of a pizza.`,
`Indescribable loneliness.`,
`An ass disaster.`,
`Shutting the fuck up.`,
`All my friends dying.`,
`Putting an entire peanut butter and jelly sandwich into the VCR.`,
`Spending lots of money.`,
`Some douche with an acoustic guitar.`,
`Flying robots that kill people.`,
`A greased-up Matthew McConaughey.`,
`An unstoppable wave of fire ants.`,
`Not contributing to society in any meaningful way.`,
`An all-midget production of Shakespeare's Richard III.`,
`Screaming like a maniac.`,
`The moist, demanding chasm of his mouth.`,
`Filling every orifice with butterscotch pudding.`,
`Unlimited soup, salad, and breadsticks.`,
`Crying into the pages of Sylvia Plath.`,
`Velcro&trade;.`,
`A PowerPoint presentation.`,
`A surprising amount of hair.`,
`Eating Tom Selleck's mustache to gain his powers.`,
`Roland the Farter, flatulist to the king.`,
`That ass.`,
`A pile of squirming bodies.`,
`Buying the right pants to be cool.`,
`Blood farts.`,
`Three months in the hole.`,
`A botched circumcision.`,
`The Land of Chocolate.`,
`Slapping a racist old lady.`,
`A lamprey swimming up the toilet and latching onto your taint.`,
`Jumping out at people.`,
`A black male in his early 20s, last seen wearing a hoodie.`,
`Mufasa's death scene.`,
`Bill Clinton, naked on a bearskin rug with a saxophone.`,
`Demonic possession.`,
`The Harlem Globetrotters.`,
`Vomiting mid-blowjob.`,
`My manservant, Claude.`,
`Having shotguns for legs.`,
`Letting everyone down.`,
`A spontaneous conga line.`,
`A vagina that leads to another dimension.`,
`Disco fever.`,
`Getting your dick stuck in a Chinese finger trap with another dick.`,
`Fisting.`,
`The thin veneer of situational causality that underlies porn.`,
`Girls that always be textin'.`,
`Blowing some dudes in an alley.`,
`Drinking ten 5-hour ENERGYs&reg; to get fifty continuous hours of energy.`,
`Sneezing, farting, and coming at the same time.`,
`A freshly-filled diaper`,
`Glue`,
`An unusually-attractive transvestite`,
`Hand-me-down adult diapers`,
`A stillborn fetus`,
`A disgraced pelican`,
`Three buckets of urine, free for 2 nights, with no late fee`,
`My testicles`,
`A black woman's vagina`,
`My asshole`,
`A whale's blowhole`,
`2 Girls 1 Cup`,
`The Big Bang Theory (TV)`,
`Teen pregnancy`,
`Ass hair`,
`Vaginal warts`,
`Ellen Degeneres`,
`Jews Against Humanity`,
`Indy wrestling`,
`Cunt`,
`Beating a crowd of delightful parents to death with a steel dildo`,
`Beating a crowd of delightful parents to death with a steel dildo while dressed as Ru Paul's brother, Ron.`,
`A roll in the hay`,
`"Get 'em, Steve-Dave!"`,
`God Hates You`,
`Manboobs.`,
`Daniel Benoit`,
`Vomiting in the shower`,
`An intellectually superior overlord`,
`Dwight Schrute`,
`Casey Anthony`,
`Clubbin seals`,
`Stunt cock`,
`Anal lice`,
`Lightsaber Dildos`,	
		},
	}

	AddPack(pack)
}
