package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "devops",
		Description: "Devops expansion",
		Prompts: []*PromptCard{
&PromptCard{Prompt: `%s as a service.`},
&PromptCard{Prompt: `%s dooms any project to epic failure.`},
&PromptCard{Prompt: `%s is a feature, not a bug.`},
&PromptCard{Prompt: `Smashing the %s for fun and profit`},
&PromptCard{Prompt: `%s is weaponized privilege.`},
&PromptCard{Prompt: `%s is webscale.`},
&PromptCard{Prompt: `%s logs or it didn't happen.`},
&PromptCard{Prompt: `%s with one weird trick.`},
&PromptCard{Prompt: `%s, as one does.`},
&PromptCard{Prompt: `%s, for some values of %s.`},
&PromptCard{Prompt: `Ask Me Anything about %s.`},
&PromptCard{Prompt: `Called on account of %s.`},
&PromptCard{Prompt: `Disrupting the established players in %s via %s.`},
&PromptCard{Prompt: `Doge %s.`},
&PromptCard{Prompt: `Employees must %s before returning to work.`},
&PromptCard{Prompt: `Enterprise %s in the cloud.`},
&PromptCard{Prompt: `Enterprise-ready %s.`},
&PromptCard{Prompt: `Epic yak-shave caused by %s.`},
&PromptCard{Prompt: `Facebook has acquired %s for $10b and %s.`},
&PromptCard{Prompt: `Free as in %s.`},
&PromptCard{Prompt: `Glitter-bombed with %s.`},
&PromptCard{Prompt: `Hi, I'm Troy McClure. You may remember me from such commit messages as %s and %s.`},
&PromptCard{Prompt: `How even is %s formed?`},
&PromptCard{Prompt: `I can haz %s.`},
&PromptCard{Prompt: `Tinder for %s`},
&PromptCard{Prompt: `If %s is the answer, you are asking the wrong question.`},
&PromptCard{Prompt: `%s does not type check.`},
&PromptCard{Prompt: `If you're using %s, you're gonna have a bad time.`},
&PromptCard{Prompt: `Nobody ever got fired for  %s.`},
&PromptCard{Prompt: `Running Windows in production leads to %s.`},
&PromptCard{Prompt: `The Internet is for cat memes and %s.`},
&PromptCard{Prompt: `Our release schedule doesn't have time for %s.`},
&PromptCard{Prompt: `The Internet of Things will be controlled by %s.`},
&PromptCard{Prompt: `The only thing necessary for evil to triumph is %s.`},
&PromptCard{Prompt: `Uber is on surge pricing because of %s.`},
&PromptCard{Prompt: `WARN: %s has been deprecated.`},
&PromptCard{Prompt: `Will merge pull requests for %s.`},
&PromptCard{Prompt: `Zero-day %s.`},
&PromptCard{Prompt: `Time to schedule the postmortem for %s. .`},
&PromptCard{Prompt: `It worked on my %s.`},
&PromptCard{Prompt: `%s, the only thing worse than recruiting spam.`},
&PromptCard{Prompt: `Put some %s on it`},
&PromptCard{Prompt: `Wrap it with the %s duct tape`},
&PromptCard{Prompt: `But Google is using %s so we should too!`},
&PromptCard{Prompt: `%s is the new %s.`},
&PromptCard{Prompt: `Etsy says we should %s everything.`},
&PromptCard{Prompt: `xkcd.com just made a hilarious comic making fun of %s.`},
&PromptCard{Prompt: `This isn't going to be all unicorns and %s.`},
&PromptCard{Prompt: `Apple just patented %s.`},
&PromptCard{Prompt: `When I was a kid we didn't have %s.`},
&PromptCard{Prompt: `%s is a nice idea, lets found a start-up.`},
&PromptCard{Prompt: `%s is for closers.`},
&PromptCard{Prompt: `DevOps: Now with 100% more %s!`},
&PromptCard{Prompt: `Main benefits of automation: %s and %s.`},
&PromptCard{Prompt: `Chef convergence failed due to %s.`},
&PromptCard{Prompt: `...and then there was the time I found %s on the root partition.`},
&PromptCard{Prompt: `We run production on %s and %s.`},
&PromptCard{Prompt: `Management said it's OK to deploy %s at 5pm on Friday`},
&PromptCard{Prompt: `Did you know that we have %s on pager rotation?`},
&PromptCard{Prompt: `There was no good solution for %s, so we built our own.`},
&PromptCard{Prompt: `Amazon built a datacenter on the moon to lessen the risk of %s causing problems.`},
&PromptCard{Prompt: `In order to improve security, we're upgrading to %s.`},
&PromptCard{Prompt: `The two pillars of our Continuous Deployment pipeline are %s and %s.`},
&PromptCard{Prompt: `I got paged at 3am because of %s.`},
&PromptCard{Prompt: `The most stable part of our infrastructure? %s`},
&PromptCard{Prompt: `When I told Jez Humble about our %s, he actually cried.`},
&PromptCard{Prompt: `When I write a book about my experiences, it'll be called "%s, the good parts"`},
&PromptCard{Prompt: `Restoring from backups failed due to %s.`},
&PromptCard{Prompt: `My two most indispensable tools are %s and %s.`},
&PromptCard{Prompt: `The production datacenter burned down because of %s.`},
&PromptCard{Prompt: `It turns out that the button labeled "Don't Push" actually does %s.`},
&PromptCard{Prompt: `You should think of your servers like %s and not like %s.`},
&PromptCard{Prompt: `I find Java to be way too %s.`},
&PromptCard{Prompt: `It's like trying to herd %s.`},
&PromptCard{Prompt: `I ended up having to buy a replacement %s on eBay.`},
&PromptCard{Prompt: `%s is more memory than anyone will ever need on a computer.`},
&PromptCard{Prompt: `%s Driven Development.`},
&PromptCard{Prompt: `The RIAA is suing me for downloading %s.`},
&PromptCard{Prompt: `Security? We've got that! We use %s.`},
&PromptCard{Prompt: `sudo pip install %s`},
&PromptCard{Prompt: `When I hooked the 3D printer up to the Internet, it accidentally created %s.`},
&PromptCard{Prompt: `My next blog post will be about how we used %s to create %s.`},
&PromptCard{Prompt: `So, I was using Wireshark to check network traffic... Did you know we have %s in production?`},
&PromptCard{Prompt: `My eyes started bleeding when I opened the editor and saw %s.`},
&PromptCard{Prompt: `I think maybe I'll leave %s off my resumé.`},
&PromptCard{Prompt: `We don't need %s - we have %s !`},
&PromptCard{Prompt: `Management just told me I need to get certified in %s.`},
&PromptCard{Prompt: `Our app is like %s, but for %s.`},
&PromptCard{Prompt: `Marketing says we're leaders in the %s space, but I think it's more accurate to say we specialize in %s.`},
&PromptCard{Prompt: `Our greatest achievement in the last year is %s.`},
&PromptCard{Prompt: `I write my code in vim because of %s`},
&PromptCard{Prompt: `If we make this deadline, Management has promised us %s.`},
&PromptCard{Prompt: `Sweet! I just found a Puppet module for %s!`},
&PromptCard{Prompt: `Last week, I created a Chef recipe for %s; this week, it's an entire cookbook for %s, Automation FTW!`},
&PromptCard{Prompt: `We really need to open-source our %s.`},
&PromptCard{Prompt: `A sales rep just tried to pitch me on %s; I told them we already have %s.`},
&PromptCard{Prompt: `Who would have known that %s could destroy an entire datacenter?`},
&PromptCard{Prompt: `sudo apt-get install %s`},
&PromptCard{Prompt: `Our production backups are stored using %s.`},
&PromptCard{Prompt: `We replaced our %s with %s`},
&PromptCard{Prompt: `After %s came up, the retrospective really went downhill.`},
&PromptCard{Prompt: `You know what our app needs? More %s, less %s.`},
&PromptCard{Prompt: `It figures - an article about our %s was posted just as we're pivoting to %s.`},
&PromptCard{Prompt: `In the next planning session, we'll cover %s and %s.`},
&PromptCard{Prompt: `Our competitive advantage is our %s.`},
&PromptCard{Prompt: `Every time someone brings up %s, I throw up a little in my mouth.`},
&PromptCard{Prompt: `Continuous %s.`},
&PromptCard{Prompt: `All that we had to do to halve our response times was implement %s`},
&PromptCard{Prompt: `Our entire app is geared towards providing %s.`},
&PromptCard{Prompt: `%s-ility`},
&PromptCard{Prompt: `We just achieved %ss per second!`},
&PromptCard{Prompt: `You now have a scroll titled '%s' (f)`},
&PromptCard{Prompt: `%s is that even HA?`},
&PromptCard{Prompt: `My Linkedin Endorsements include %s.`},
&PromptCard{Prompt: `Users are %s.`},
&PromptCard{Prompt: `Robots are going to make %s obsolete.`},
&PromptCard{Prompt: `Accidental %s.`},
&PromptCard{Prompt: `An error occurred: E%s`},
&PromptCard{Prompt: `According to the logs, %s was initially caused by %s.`},
&PromptCard{Prompt: `We can just fix that with a little %s.`},
&PromptCard{Prompt: `You can have %s, %s, or %s.  Pick two.`},
&PromptCard{Prompt: `A monad is just a %s in the category of %s, what's the problem?`},
&PromptCard{Prompt: `Functional programming - if you can't %s it, %s it.`},
&PromptCard{Prompt: `On a scale from 1 to 10, this is %s!`},
&PromptCard{Prompt: `We don't need configuration management, we have %s!`},
&PromptCard{Prompt: `%s, now with %s support.`},
&PromptCard{Prompt: `RedHat has announced that RHEL 8 will ship with %s.`},
&PromptCard{Prompt: `Hey, %s is down. Can you fix it?`},
&PromptCard{Prompt: `I grabbed %s on my way out the door after our paychecks bounced and management stopped answering their phones.`},
&PromptCard{Prompt: `Did you try %s yet?`},
&PromptCard{Prompt: `I was 6 beers in when I got the pager alert that %swas down.`},
&PromptCard{Prompt: `Notice: Building %s for %s`},
&PromptCard{Prompt: `I laughed when they said I'd be on call 24/7 but wouldn't receive a stipend for %s.`},
&PromptCard{Prompt: `If it weren't for %s we'd all be %s.`},
&PromptCard{Prompt: `%s, %s and just a few lines of Perl.`},
&PromptCard{Prompt: `NoSQL is superior to SQL because %s`},
&PromptCard{Prompt: `Script kiddies got into %s because %s.`},
&PromptCard{Prompt: `%s is better than Hadoop because %s`},
&PromptCard{Prompt: `Disturbing %s leaves %s fucked`},
&PromptCard{Prompt: `Rub a little %s on it`},
&PromptCard{Prompt: `WAIT, YOU DELETED %s??!`},
&PromptCard{Prompt: `@%sborat`},
&PromptCard{Prompt: `It's not web scale, it's %s`},
&PromptCard{Prompt: `The tech support hotline told me to %s`},
&PromptCard{Prompt: `Asynchronous REST API calls are the solution to %s`},
&PromptCard{Prompt: `Say concurrent threads again and I will %s you.`},
&PromptCard{Prompt: `Guys, seriously, if we just use %s it will solve all our problems with %s!`},
&PromptCard{Prompt: `Facebook changed their profiles today because %s.`},
&PromptCard{Prompt: `github.com/%s/%s`},
&PromptCard{Prompt: `Hello. My name is %s and I am addicted to %s .`},
&PromptCard{Prompt: `%s dependency hell.`},
&PromptCard{Prompt: `That talk outline said it would be about %s, but it ended up being more like %s.`},
&PromptCard{Prompt: `I will replace you with a very small %s.`},
&PromptCard{Prompt: `Jordan Sissel hates % so much that he created a new opensource project called %s to work around it.`},
&PromptCard{Prompt: `%s isn't a job title`},
&PromptCard{Prompt: `For the next project we are going to use %s to solve %s .`},
&PromptCard{Prompt: `My editor of choice is %s.`},
&PromptCard{Prompt: `%s it; ship it.`},
&PromptCard{Prompt: `%s-Stack Developer`},
&PromptCard{Prompt: `%sSQL`},
&PromptCard{Prompt: `That's not a hacker, that's my %s!`},
&PromptCard{Prompt: `It has been %s days since the last %s`},
&PromptCard{Prompt: `I've %s things you people wouldn't %s`},
&PromptCard{Prompt: `The %s on the server were deleted because %s .`},
&PromptCard{Prompt: `This week, Aphyr runs %s through jepsen.`},
&PromptCard{Prompt: `The intern just ran %s on the load balancer.`},
&PromptCard{Prompt: `I need you to do a %s with %s before %s .`},
&PromptCard{Prompt: `Lambdas are just a lame implementation of %s.`},
&PromptCard{Prompt: `C-x; C-%s`},
&PromptCard{Prompt: `This users wants %s because %s .`},
&PromptCard{Prompt: `%s should be deprecated in favour of %s .`},
&PromptCard{Prompt: `%s mismatch between %s and %s`},
&PromptCard{Prompt: `I put %s on the scripts to make it run faster.`},
&PromptCard{Prompt: `Developers do not get access to production machines, because of %s.`},
&PromptCard{Prompt: `Developers need access to production machines because %s.`},
&PromptCard{Prompt: `We run %s in a cron job every 15 minutes.`},
&PromptCard{Prompt: `The client says it needs more %s .`},
&PromptCard{Prompt: `We're a %s as a Service company.`},
&PromptCard{Prompt: `I could hire a %s to do your job!`},
&PromptCard{Prompt: `My next Velocity talk is called "%sops"`},
&PromptCard{Prompt: `The RFO for the global outage was %s compunded by %s`},
&PromptCard{Prompt: `I was hired to maintain this 20 year old script that runs our critical %s infrastructure.`},
&PromptCard{Prompt: `Amazon Elastic %s`},
&PromptCard{Prompt: `I know we use %s, but I wrote this critical program in %s.`},
&PromptCard{Prompt: `I'll just have Ops spin up a couple of %s environments.`},
&PromptCard{Prompt: `I'm writing my next IRC bot with %s.`},
&PromptCard{Prompt: `SIG%s`},
&PromptCard{Prompt: `I cannot wait until someone makes a %s cluster out of these.`},
&PromptCard{Prompt: `C will finally be displaced by %s`},
&PromptCard{Prompt: `%s%s.io`},
&PromptCard{Prompt: `We don't need to worry about %s, We're using MongoDB.`},
&PromptCard{Prompt: `Why is %s better than Hadoop?`},
&PromptCard{Prompt: `FC067: %s`},
&PromptCard{Prompt: `Oh, the %s is just a hack to get the %s to run.`},
&PromptCard{Prompt: `How do I even %s ?`},
&PromptCard{Prompt: `%s all the things.`},
&PromptCard{Prompt: `ERROR: %s NOT FOUND`},
&PromptCard{Prompt: `We don't need backups, we've got %s.`},
&PromptCard{Prompt: `Fixing your father's computer with %s.`},
&PromptCard{Prompt: `it's always a %s DNS problem`},
&PromptCard{Prompt: `%s with this one weird trick.`},
&PromptCard{Prompt: `%s isn't new, we used to do it in the '70s on mainframes.`},
&PromptCard{Prompt: `Puppet is better than Chef because %s and %s`},
&PromptCard{Prompt: `How is %s better than %s ?`},
&PromptCard{Prompt: `Learn %s the hard way`},
&PromptCard{Prompt: `vagrant up %s`},
&PromptCard{Prompt: `bollocks up %s`},
&PromptCard{Prompt: `You can fix  %s with %s .`},
&PromptCard{Prompt: `We took the plunge and rewrote %s in Go`},
&PromptCard{Prompt: `Implementing %s%s should take only 2 lines of code.`},
&PromptCard{Prompt: `I accidentally the entire %s, is this dangerous?`},
&PromptCard{Prompt: `Good enough for %s work`},
&PromptCard{Prompt: `Yeah, but can it run %s`},
&PromptCard{Prompt: `Security through %s.`},
&PromptCard{Prompt: `%s? You can safely ignore that. Usually.`},
&PromptCard{Prompt: `%s isn't cool. You know what's cool? %s`},
&PromptCard{Prompt: `I made a new editor, better than vim and emacs. It's called %s`},
&PromptCard{Prompt: `640k should be enough for %s.`},
&PromptCard{Prompt: `%s worked in dev.`},
&PromptCard{Prompt: `You can't fix %s`},
&PromptCard{Prompt: `How hard could it be to port Linux to %s.`},
&PromptCard{Prompt: `I just finished working on my rocket powered %s.`},
&PromptCard{Prompt: `Richard Stallman will kill you with his teeth for %s.`},
&PromptCard{Prompt: `DB tuning with %s.`},
&PromptCard{Prompt: `Can anyone help me get %s running on Cisco IOS?`},
&PromptCard{Prompt: `Real %s don't use %s`},
&PromptCard{Prompt: `%s on XEN`},
&PromptCard{Prompt: `Please bring back %s. You broke my workflow.`},
&PromptCard{Prompt: `I cut-and-pasted this StackOverflow code for my %s.`},
&PromptCard{Prompt: `I'm just finishing up my manifesto on %s.`},
&PromptCard{Prompt: `r/%s.`},
&PromptCard{Prompt: `We can discuss %s at the stand-up meeting.`},
&PromptCard{Prompt: `A Beowulf cluster of %s.`},
&PromptCard{Prompt: `We're demoing %s for %s at SXSW.`},
&PromptCard{Prompt: `I aliased %s to git %s.`},
&PromptCard{Prompt: `10 PRINT "%s"; GOTO 10`},
&PromptCard{Prompt: `alt.binaries.%s`},
&PromptCard{Prompt: `It is completely dark. You are likely to be eaten by a %s.`},
&PromptCard{Prompt: `Conway's Game of %s.`},
&PromptCard{Prompt: `Next year I'll start learning %s`},
&PromptCard{Prompt: `s/%s/%s/g`},
&PromptCard{Prompt: `%s is the newest gTLD`},
&PromptCard{Prompt: `Works on my %s.`},
&PromptCard{Prompt: `One does not simply %s`},
&PromptCard{Prompt: `Sorry, you'll need to open a ticket before we can %s.`},
&PromptCard{Prompt: `ln -s %s %s`},
&PromptCard{Prompt: `%s`},
&PromptCard{Prompt: `%s is dead.`},
&PromptCard{Prompt: `%s. What the fuck does that mean?`},
&PromptCard{Prompt: `%s-to-butt plugin`},
&PromptCard{Prompt: `Make it %s.`},
&PromptCard{Prompt: `%scoin.`},
&PromptCard{Prompt: `%s computing`},
&PromptCard{Prompt: `grep %s | mail %s`},
&PromptCard{Prompt: `%s just got pwned.`},
&PromptCard{Prompt: `It's like %s, but with %s and list comprehensions.`},
&PromptCard{Prompt: `Software Defined %s.`},
&PromptCard{Prompt: `I don't have any UNIX Beards in stock, but we do have  %s`},
&PromptCard{Prompt: `Amazon does %s, why can't we?`},
&PromptCard{Prompt: `%s nagios`},
&PromptCard{Prompt: `I can't believe you're still using %s.`},
&PromptCard{Prompt: `/dev/%s: Device is busy`},
&PromptCard{Prompt: `%s, You don't exist, go away!`},
&PromptCard{Prompt: `I tried %s, The doctors say I'll never walk again.`},
&PromptCard{Prompt: `git --%s`},
&PromptCard{Prompt: `The %s Public License.`},
&PromptCard{Prompt: `%s begins with %s.`},
&PromptCard{Prompt: `Couldn't we use %s?`},
&PromptCard{Prompt: `%s would be so much better if we rewrote it in Clojure.`},
&PromptCard{Prompt: `So I just found %s and %s running in a screen session.`},
&PromptCard{Prompt: `Why is root running %s under tmux?`},
&PromptCard{Prompt: `Instead of installing %s, what if we just used %s`},
&PromptCard{Prompt: `I need a webinar like I need %s.`},
&PromptCard{Prompt: `Fuck it, time to break out the emergency %s.`},
&PromptCard{Prompt: `On the plus side, we finally got rid of %s.`},
&PromptCard{Prompt: `%s thought leader.`},
&PromptCard{Prompt: `Fuck it: %s looks good to me.`},
&PromptCard{Prompt: `It looks like you're trying to %s. Can I help?`},
&PromptCard{Prompt: `bash: command not found: %s`},
&PromptCard{Prompt: `ETOOMUCH%s`},
&PromptCard{Prompt: `How did %s ever work?`},
&PromptCard{Prompt: `Whoops, I thought that method was supposed to %s the %s`},
&PromptCard{Prompt: `I thought you said %s was secure?`},
&PromptCard{Prompt: `git: You are in detached %s state.`},
&PromptCard{Prompt: `Why don't we just fork %s ?`},
&PromptCard{Prompt: `Network dropped connection because of %s.`},
&PromptCard{Prompt: `We turned off %s and everything magically got better.`},
&PromptCard{Prompt: `I found a Samba share full of %s`},
&PromptCard{Prompt: `%s. What could go wrong?`},
&PromptCard{Prompt: `Install %s`},
&PromptCard{Prompt: `I installed %s by accident.`},
&PromptCard{Prompt: `Read-eval-%s-loop.`},
&PromptCard{Prompt: `We should try it with an actual %s.`},
&PromptCard{Prompt: `Is %s something we need to optimize for?`},
&PromptCard{Prompt: `Hack %s into redis.`},
&PromptCard{Prompt: `%s Considered Harmful`},
&PromptCard{Prompt: `Never %s before a demonstration`},
&PromptCard{Prompt: `The %s is used when the CPU is on fire`},
&PromptCard{Prompt: `modperl can be used to implement %s`},
&PromptCard{Prompt: `%s runs Ruby as root`},
&PromptCard{Prompt: `Larry Wall trained as missionary then %s`},
&PromptCard{Prompt: `Listening to the fans in the server farm leads to %s`},
&PromptCard{Prompt: `%s and %s are rumoured to be working on a python module for a helicam`},
&PromptCard{Prompt: `A lot of disk space is needed for %s`},
&PromptCard{Prompt: `automagical %s`},
&PromptCard{Prompt: `Whoever made the unscheduled change to production on Friday will be forced to use %s.`},
&PromptCard{Prompt: `Install %s`},
&PromptCard{Prompt: `Never question the %s`},
&PromptCard{Prompt: `I can't wait until we no longer use %s`},
&PromptCard{Prompt: `I bet if we switch to %s it will just work`},
&PromptCard{Prompt: `%s has just discovered %s.  We're doomed.`},
&PromptCard{Prompt: `A neckbeard made of %s.`},
&PromptCard{Prompt: `False alarm, it was just %s running %s.`},
&PromptCard{Prompt: `%s running on a rack of %s.`},
&PromptCard{Prompt: `No, %s being hopelessly broken is NOT an emergency.`},
&PromptCard{Prompt: `Our new startup is the %s for %s.`},
&PromptCard{Prompt: `%s make me a sandwich`},
&PromptCard{Prompt: `%s over IP`},
&PromptCard{Prompt: `%s is a hardware problem.`},
&PromptCard{Prompt: `I AM working, I'm waiting for the %s run to finish.`},
&PromptCard{Prompt: `The first rule of %s is: You do not talk about %s.`},
&PromptCard{Prompt: `Google Analytics says 100% of my website visitors are %s`},
&PromptCard{Prompt: `%s will never get job in Microsoft`},
&PromptCard{Prompt: `4chan.org is powered by %s.`},
&PromptCard{Prompt: `We can %s just like Netflix`},
&PromptCard{Prompt: `%s is how I resolve all merge conflicts.`},
&PromptCard{Prompt: `Why does someone keep re-implementing system utilities in %s?`},
&PromptCard{Prompt: `Remember when you told me to tell you when you were acting %s and %s? ---you're doing it now.`},
&PromptCard{Prompt: `Our only hope at recovering the data is %s`},
&PromptCard{Prompt: `%s: the gift that keeps on giving.`},
&PromptCard{Prompt: `%s has been killed with fire.  My work is done here.`},
&PromptCard{Prompt: `Problem exists between Keyboard and %s`},
&PromptCard{Prompt: `100% government funded %s!`},
&PromptCard{Prompt: `The %s certification program.`},
&PromptCard{Prompt: `%s? I'd hit that.`},
&PromptCard{Prompt: `%s makes robots moves`},
&PromptCard{Prompt: `I just finished writing an API for %s.`},
&PromptCard{Prompt: `%s is a batch command to shut the fuck up`},
&PromptCard{Prompt: `%s.  Failed to cache catalog.`},
&PromptCard{Prompt: `Everytime you allocate you have to %s when you're done`},
&PromptCard{Prompt: `Sorry, I'm all out of %s-fu.`},
&PromptCard{Prompt: `90% of everything is %s.`},
&PromptCard{Prompt: `Given enough %s, all bugs are %s.`},
&PromptCard{Prompt: `%s never use on git`},
&PromptCard{Prompt: `The first 90% of development is %s. The second 90% is %s.`},
&PromptCard{Prompt: `When you logged in there, did you see a %s that said %s`},
&PromptCard{Prompt: `Purely numeric hostname and not a %s -----rejecting!`},
&PromptCard{Prompt: `I'm pretty sure %s isn't thread safe`},
&PromptCard{Prompt: `We don't have to worry about CAP Theorem because of %s.`},
&PromptCard{Prompt: `I don't always test my code, but when I do I do it in %s.`},
&PromptCard{Prompt: `Those who don't understand %s are condemned to reinvent it, poorly`},
&PromptCard{Prompt: `The NSA is really interested in our latest project: %s.`},
&PromptCard{Prompt: `Just change the %s, it'll be fine.`},
&PromptCard{Prompt: `Yeah, you need to modprobe %s to get it to recognize the %s`},
&PromptCard{Prompt: `Oh, we're devops! We have %s in the office, but only the DBA can touch it.`},
&PromptCard{Prompt: `We're spending 20% of this sprint doing %s.`},
&PromptCard{Prompt: `%s found a new OpenSSL vulernability people are calling %s.`},
&PromptCard{Prompt: `Management has changed all our job titles to %s.`},
&PromptCard{Prompt: `while true; do %s; done`},
&PromptCard{Prompt: `The consultant we hired is certain that %s will drastically increase the performance of %s`},
&PromptCard{Prompt: `Could you just push this update for %s?  It should be a no-op.`},
&PromptCard{Prompt: `If we're all going to get fired, let's get fired for %s.`},
&PromptCard{Prompt: `We can't pay you, but we can offer %s in compensation.`},
&PromptCard{Prompt: `A soiled napkin with the contents of %s scribbled on it`},
&PromptCard{Prompt: `Who thought that %s was a good idea?`},
&PromptCard{Prompt: `It's not the recommended configuration to use %s with %s but it's in production right now.`},
&PromptCard{Prompt: `We wrote our own build tool based on %s`},
&PromptCard{Prompt: `I've received a Microsoft MVP Award for %s`},
&PromptCard{Prompt: `We rewrote %s in %s`},
&PromptCard{Prompt: `The ticket to install %s?  I deletegated it.`},
&PromptCard{Prompt: `Some people, when confronted with a problem, think "I know, I'll use %s." Now they have two problems.`},
&PromptCard{Prompt: `Artisanally crafted %s.`},
&PromptCard{Prompt: `The backups are fine, but the restore process is %s`},
&PromptCard{Prompt: `I can't believe QA made a ticket for %s`},
&PromptCard{Prompt: `The %s that ops provides developers.`},
&PromptCard{Prompt: `Oracle is proud to announce that the next edition of Java features %s`},
&PromptCard{Prompt: `Move %s and break things.`},
&PromptCard{Prompt: `%s: ci or not ci?`},
&PromptCard{Prompt: `I opened the server cabinet and it was full of %s.`},
&PromptCard{Prompt: `Crossing %s could lead to total protonic reversal.`},
&PromptCard{Prompt: `The next big thing is %s`},
&PromptCard{Prompt: `I once made a robot around the concept of %s`},
&PromptCard{Prompt: `I %s your stupid issue!`},
&PromptCard{Prompt: `Nine circles of %s hell.`},
&PromptCard{Prompt: `I once wrote an NPM module called %s.js`},
&PromptCard{Prompt: `I asked the contractor for %s and they delivered %s.`},
&PromptCard{Prompt: `Welcome to Programming 101, our first topic will be %s`},
&PromptCard{Prompt: `The Genius Bar recommends you try %s`},
&PromptCard{Prompt: `Post-modern coding is defined by %s`},
&PromptCard{Prompt: `%s | sudo sh`},
&PromptCard{Prompt: `ASP has finally developed and replaced %s`},
&PromptCard{Prompt: `%s has been put under the WTFPLicense`},
&PromptCard{Prompt: `Here's %s, as I promised.`},
&PromptCard{Prompt: `I'd like %s, %s, and a Fluttershy.`},
&PromptCard{Prompt: `It compiles %s to JavaScript.`},
&PromptCard{Prompt: `Only the Enterprise Edition(tm) has %s.`},
&PromptCard{Prompt: `%s is a proof of concept and an actual %s %s`},
&PromptCard{Prompt: `The trouble with kids these days is %s`},
&PromptCard{Prompt: `%s is the new Stalinism.`},
&PromptCard{Prompt: `%s for the win!`},
&PromptCard{Prompt: `%s is the new %s`},
&PromptCard{Prompt: `Don't read the %s or the %s pages`},
&PromptCard{Prompt: `With %s, you write once, run nowhere.`},
&PromptCard{Prompt: `%s discontinued support for the Linux version.`},
&PromptCard{Prompt: `A manager told me I couldn't remove our dependency on %s, but I got around it with %s.`},
&PromptCard{Prompt: `%s implements every single standard for %s.  Poorly.`},
&PromptCard{Prompt: `Just think of the Internet as %s.`},
&PromptCard{Prompt: `Would you like %s with that?`},
&PromptCard{Prompt: `%s? We've got that.`},
&PromptCard{Prompt: `It took over 40 hours to document %s.`},
&PromptCard{Prompt: `//TODO: %s.`},
&PromptCard{Prompt: `npm install %s.`},
&PromptCard{Prompt: `Circular imports import %s.`},
&PromptCard{Prompt: `A firewall rule for %s.`},
&PromptCard{Prompt: `%s is why the jDBA thought it might be time to go to #mysql on freenode`},
&PromptCard{Prompt: `%s is the only reason the jDBA survived typing rm -rf /`},
&PromptCard{Prompt: `%s exists?`},
&PromptCard{Prompt: `It's like %s on %s.`},
&PromptCard{Prompt: `I came here to drink milk and %s, and I've just finished my milk.`},
&PromptCard{Prompt: `End-to-end %s.`},
&PromptCard{Prompt: `%s will help you remember to sanitze your database inputs.`},
&PromptCard{Prompt: `Fascists cannot stand %s.`},
&PromptCard{Prompt: `0.%s%s%s`},
&PromptCard{Prompt: `RTFM so you can %s%s.`},
&PromptCard{Prompt: `%s took EBS down again today.`},
&PromptCard{Prompt: `I ssh'd into a server running %s and promptly noped the fuck out of there.`},
&PromptCard{Prompt: `%s, the final solution.`},
&PromptCard{Prompt: `We're running %s in production?!`},
&PromptCard{Prompt: `%s has root access.`},
&PromptCard{Prompt: `We don't have enough package managers said %s`},
&PromptCard{Prompt: `%s is more reliable than %s`},
&PromptCard{Prompt: `Of course culture is important to us, that's why we have %s.`},
&PromptCard{Prompt: `I'd rather stick my penis in %s.`},
&PromptCard{Prompt: `I'd trust all my stuff to %s.`},
&PromptCard{Prompt: `%s ass-as-sin-vice.`},
&PromptCard{Prompt: `My %s for a %s.`},
&PromptCard{Prompt: `Nice %s I'll take it.`},
&PromptCard{Prompt: `@horse%s`},
&PromptCard{Prompt: `such %s. wow.`},
&PromptCard{Prompt: `That's funny, did %s used to be here?`},
&PromptCard{Prompt: `I can't believe you improved %s by deleting %s%s`},
&PromptCard{Prompt: `The only thing more dangerous than %s is a programmer with %s`},
&PromptCard{Prompt: `1.  %s 2. %s  3. Profit.`},
&PromptCard{Prompt: `Monads are easy! Just think of them as %s`},
&PromptCard{Prompt: `%s: powered by the cloud.`},
&PromptCard{Prompt: `Before you penetrate someone's backend, you first must %s`},
&PromptCard{Prompt: `I upload my worm to %s`},
&PromptCard{Prompt: `I fork my children with %s`},
&PromptCard{Prompt: `My shared socket connects to %s’s backend`},
&PromptCard{Prompt: `Multiple backend penetration  is achieved with %s`},
&PromptCard{Prompt: `You can force kill your children by %s`},
&PromptCard{Prompt: `%s corrupts your children's memory`},
&PromptCard{Prompt: `%s behaves like a dangling socket`},
&PromptCard{Prompt: `Verify your %s when you wipe your childrens sockets`},
&PromptCard{Prompt: `#!/bin/%s`},
&PromptCard{Prompt: `make %s && sudo make install`},
&PromptCard{Prompt: `I bet the person who wrote this uses %s.`},
&PromptCard{Prompt: `I'm not %s, my code is compiling.`},
&PromptCard{Prompt: `Don't worry, we have unit tests for %s.`},
&PromptCard{Prompt: `As a %s, I want %s.`},
&PromptCard{Prompt: `The only non-conformance in this year's audit was %s.`},
&PromptCard{Prompt: `Blaming intern for the %s`},
&PromptCard{Prompt: `%s is my favourite thing about %s`},
&PromptCard{Prompt: `I wish that we had more %s in our office`},
&PromptCard{Prompt: `I've once been so drunk that %s actually made sense`},
&PromptCard{Prompt: `To understand %s you must first understand %s.`},
&PromptCard{Prompt: `%s @ 127.0.0.1 -p %s`},
&PromptCard{Prompt: `%s? You mean %s!`},
&PromptCard{Prompt: `%s is coming out of stealth mode`},
&PromptCard{Prompt: `My code is not compiling because of %s.`},
&PromptCard{Prompt: `%s ate all my memory`},
&PromptCard{Prompt: `%s is always a good practice.`},
&PromptCard{Prompt: `Don't mind me, I'm just practicing %s .`},
&PromptCard{Prompt: `We accidently the whole %s.`},
&PromptCard{Prompt: `It's easy! Just run %s`},
&PromptCard{Prompt: `I assure you %s is secure!`},
&PromptCard{Prompt: `Our backup policy is %s`},
&PromptCard{Prompt: `%s the XML in that JSON file`},
&PromptCard{Prompt: `pacman -Syu accidentally %s everything`},
&PromptCard{Prompt: `I saw a High Scalability blog post about %s`},
&PromptCard{Prompt: `We didn't think anyone was using %s!`},
&PromptCard{Prompt: `Do you wanna build a %s?`},
&PromptCard{Prompt: `IBM just created JSONxx to encapsulate JSON in XML in %s`},
&PromptCard{Prompt: `I never truly understood eXtreme programming until I encountered %s`},
&PromptCard{Prompt: `The Agile Manifesto taught me to pick %s over %s`},
&PromptCard{Prompt: `%s should be a singleton!`},
&PromptCard{Prompt: `Flash is dying because %s`},
&PromptCard{Prompt: `Neo, the matrix has one fatal flaw, you must find %s`},
&PromptCard{Prompt: `Javascript is the best language ever, thanks to %s`},
&PromptCard{Prompt: `Last night while drunk, the W3C declared %s as a new web standard.`},
&PromptCard{Prompt: `North Korea finally launched warheads because of %s`},
&PromptCard{Prompt: `Last night I accidentally ran sudo chmod -R 777 /. I just blame %s.`},
&PromptCard{Prompt: `During the lunch break I like to think about %s.`},
&PromptCard{Prompt: `Nobody will value your work if you don't use %s`},
&PromptCard{Prompt: `%s, because scientists don't know how to code`},
&PromptCard{Prompt: `%s, because Knuth.`},
&PromptCard{Prompt: `The entire system failed because of %s`},
&PromptCard{Prompt: `The meeting between Europe and the USA was cancelled because of %s`},
&PromptCard{Prompt: `We missed the launch window due to confusion from %s`},
&PromptCard{Prompt: `%s wasted thousands of dollars`},
&PromptCard{Prompt: `No one can authenticate because of %s`},
&PromptCard{Prompt: `%s caused the servers to melt down`},
&PromptCard{Prompt: `%s invalidated all the assumptions in our monitoring system`},
&PromptCard{Prompt: `%s because %s.`},
&PromptCard{Prompt: `CAMS is outdated because of %s.`},
&PromptCard{Prompt: `%s: Easy one-step installation`},
&PromptCard{Prompt: `%s, because even the hobos of Market Street need a cluster scheduler.`},
&PromptCard{Prompt: `We need to update the %s`},
&PromptCard{Prompt: `It's cool, they use %s at Etsy.`},
&PromptCard{Prompt: `Code as %s.`},
&PromptCard{Prompt: `%s is how the cloud works.`},
&PromptCard{Prompt: `How does it look in Opera?`},
&PromptCard{Prompt: `The %s shell`},
&PromptCard{Prompt: `%s in haskell`},
&PromptCard{Prompt: `Say %s one more time; I dare you!`},
&PromptCard{Prompt: `The cloud runs on %s, with a bit of %s.`},
&PromptCard{Prompt: `%s, because who needs monitoring.`},
&PromptCard{Prompt: `This problem can be completely solved with %s implemented in %s.`},
&PromptCard{Prompt: `%s vs %s... fight!`},
&PromptCard{Prompt: `I regret to inform you your weekend has been revoked due to %s.`},
&PromptCard{Prompt: `All alerts go to %s, which is handled by %s.`},
&PromptCard{Prompt: `I've got 99 problems but %s ain't one.`},
&PromptCard{Prompt: `140 characters is just enough to explain %s.`},
&PromptCard{Prompt: `%s all the way down.`},
&PromptCard{Prompt: `%s continuously spawns zombie processes`},
&PromptCard{Prompt: `Elliptic-Curve Diffie-Helman breaks against %s`},
&PromptCard{Prompt: `Why isn't my script working?`},
&PromptCard{Prompt: `ITIL best practices suggest %s is the next step`},
&PromptCard{Prompt: `We would have gotten the funding, if only our slide deck included %s`},
&PromptCard{Prompt: `Have you tried %s and %s ?`},
&PromptCard{Prompt: `Why can't I login to the VPN?`},
&PromptCard{Prompt: `I left %s in the server room.`},
&PromptCard{Prompt: `I stuck my hand in a sysadmin's beard and pulled out %s`},
&PromptCard{Prompt: `Before exiting, the program kills %s`},
&PromptCard{Prompt: `Cookbooks containing %s have been known to cause %s`},
&PromptCard{Prompt: `Once we added %s to the firewall rules, %s worked perfectly`},
&PromptCard{Prompt: `My pre-commit hook replaces tab characters with %s`},
&PromptCard{Prompt: `I was up all night debugging %s`},
&PromptCard{Prompt: `Error: insufficient %s`},
&PromptCard{Prompt: `The Product Team handed me a spec, they want %s in the next release of %s`},
&PromptCard{Prompt: `The malware came from an infected ad on %s .com`},
&PromptCard{Prompt: `Killing child processes releases resources back to %s`},
&PromptCard{Prompt: `That regular expression is designed to match %s but not %s`},
&PromptCard{Prompt: `The vendor solution didn't have log aggregation, but it did have %s`},
&PromptCard{Prompt: `Our custom log rotation scripts have the added feature of %s`},
&PromptCard{Prompt: `This year, Cross-Site Request Forgery (CSRF) was knocked out of the OWASP Top 10, and replaced by %s`},
&PromptCard{Prompt: `Nagios sucks, let's replace it with %s`},
&PromptCard{Prompt: `My pull request was rejected because it contained %s`},
&PromptCard{Prompt: `My stacktrace revealed %s`},
&PromptCard{Prompt: `Chef encountered an error attempting to create %s`},
&PromptCard{Prompt: `Since the 1950s, engineers have been striving toward a more effective means of generating %s`},
&PromptCard{Prompt: `Our code was efficient, except for the module containing %s, which was slower than %s`},
&PromptCard{Prompt: `I need to re-munge the CSV, replacing the commas with %s`},
&PromptCard{Prompt: `We strive for continuous deployment, continuous delivery, and continuous %s`},
&PromptCard{Prompt: `Data-driven decisions are to be replaced with %s`},
&PromptCard{Prompt: `The ruby gem is useless, it's a lesser implementation of %s`},
&PromptCard{Prompt: `Windows ME had a service pack that solved the problem of %s`},
&PromptCard{Prompt: `Lennart Poettering's latest project is %s.`},
&PromptCard{Prompt: `%s is the quickest way to identify what is burning in the server room.`},
&PromptCard{Prompt: `Oh, we store all our docs in %s.`},
&PromptCard{Prompt: `I accidentally %s the whole database.`},
&PromptCard{Prompt: `It's not a bug it's a %s.`},
&PromptCard{Prompt: `What killed the mood at E3?`},
&PromptCard{Prompt: `To replace camelCase, the new C++ standards mandate variables be named using %s.`},
&PromptCard{Prompt: `I'm sorry %s isn't numberwang.`},
&PromptCard{Prompt: `I'm sorry %s isn't wangernum.`},
&PromptCard{Prompt: `%s became self aware and kidnapped the sysadmins.`},
&PromptCard{Prompt: `That's the first time I've ever seen ProGuard used to obfuscate %s.`},
&PromptCard{Prompt: `Every day at work I implement %s and my mother still tells her friends I "do computers".`},
&PromptCard{Prompt: `That's the first time I've ever seen comments written in %s.`},
&PromptCard{Prompt: `It's not a problem, I'll just %s it later`},
&PromptCard{Prompt: `I tend to solve the problem of %s by %s.`},
&PromptCard{Prompt: `HAL 9000 went mad because someone compiled %s on his system.`},
&PromptCard{Prompt: `What you are referring to as %s is actually GNU/%s`},
&PromptCard{Prompt: `We sub-contrated %s to build our MVP.`},
&PromptCard{Prompt: `%s is highly available, idempotent, and load balancing.`},
&PromptCard{Prompt: `Our new disaster recovery plan: %s`},
&PromptCard{Prompt: `All your %s are belong to us`},
			
		},

		Responses: []ResponseCard{			
`Brogrammers`,
`Continuous integration`,
`STEM`,
`The Cult of Mac`,
`Degraded performance in some AWS availability zones`,
`Developers`,
`DevOps`,
`Eating sushi with Andrew Clay Shafer`,
`fuckedcompany.com`,
`Git`,
`Golang`,
`Growth hacking`,
`vi vi vi`,
`Hacker News`,
`Larry Ellison`,
`Leaky abstractions`,
`Meritocracy`,
`MongoDB`,
`Node.js`,
`NPM`,
`Pareto Inefficient Nash Equilibriums`,
`Posting on Etsy's codeascraft blog`,
`Python`,
`Python datetime module`,
`RecruiterFail`,
`Ruby`,
`Running out of IPv4 addresses`,
`Sysadmins`,
`The Stanford of Canada`,
`Thought leadership`,
`Twitter`,
`Unicode errors`,
`Unknown source in your stack trace`,
`Waiting for console.aws.amazon.com`,
`Women in tech`,
`Yet another package manager`,
`Our Release Engineer`,
`DevOps Days`,
`Bullshit.io`,
`OpenSSL`,
`Heartbleed`,
`The NSA`,
`O'Reilly`,
`Edward Snowden`,
`Google`,
`Magic Spray`,
`Web scale`,
`Functional programming`,
`Stack trace generator`,
`PHP? Oh dear god why?!`,
`ActionScript 3`,
`SVN`,
`Perl 6`,
`COTS Shareware`,
`2400 baud modem`,
`A squirrel with a taste for fiber`,
`Zombie processes`,
`CAP Theorem`,
`Snowflake server`,
`A Cisco router with a flaky chip`,
`NullPointerException: null`,
`Apache 1.2 running as root`,
`More buzzwords than you can shake a scrum at`,
`it better not have, why wouldn't you text`,
`VisualBasic DLLs`,
`A JAR full of spaghetti`,
`An epic caffeine bender`,
`A WSDL from 2003`,
`The Sales & Marketing department`,
`Business logic in PowerPoint slides`,
`/var/log symlinked to /dev/null`,
`Hypervisors running hypervisors running hypervisors`,
`An angry badger with an electromagnet on its back`,
`A shared root password`,
`Private keys in /var/www`,
`Parsing HTML with regex`,
`A 3.5" floppy disk`,
`An untested restore process`,
`A cron job that reboots the server every 5 minutes`,
`Apache Zookeeper on a 286`,
`Sadness as a Service`,
`Cloud-based business strategy`,
`Cloud 2.0`,
`The next Y2K`,
`An army of chaos monkeys, all carrying flamethrowers`,
`A CORBA service written in Ada which communicates using JSONx`,
`A home-rolled systemd replacement`,
`A custom kernel with Frontpage Extensions installed`,
`A mobile web 2.0 RIA`,
`Agony-Driven Development`,
`Being acquired by Oracle`,
`Catastrophic Failure as a Service`,
`Zombie processes`,
`A global write lock`,
`75-tier architecture`,
`Hand-crafted artisan x86 assembly code:q`,
`The world's only fully-functional ROFLcopter`,
`A proof that P=NP written in BASIC`,
`An Exchange email loop`,
`A self-aware PHP script`,
`A 500-megabyte UDP packet`,
`The last remaining Multics server on Earth`,
`A Null-modem cable`,
`A turducken made entirely of bash scripts`,
`Write-only code`,
`PagerDuty configured with a random number generator`,
`Netscape Navigator 3.2 support`,
`dd`,
`A Piñata full of error messages`,
`Mutation of immutable data`,
`Maven downloading the entire internet`,
`Continuous Disintegration`,
`IE6`,
`Scrum Master`,
`Magic Smoke`,
`done done`,
`Tech Debt Day`,
`Log Shipping`,
`uucp`,
`4chan Party Van`,
`Adderall`,
`Tcl`,
`NoOps`,
`An angry whale shitting containers`,
`:(){ :|:& };:`,
`Too Big Data`,
`Accidentally the entire data center`,
`freebasing caffeine`,
`Fat fingered`,
`Half open TCP connections`,
`Steve Ballmer wielding a battleaxe`,
`A 50k line Bash script that's achieved self awareness`,
`Gigadevops`,
`Enterprise Grade Bash scripts`,
`Agile`,
`A pink sombrero and a fifth of tequila`,
`A simple 15 level Hiera hierarachy`,
`lolscale.`,
`CouchDB`,
`GeoCouchDB`,
`High Availability`,
`Map-Reduce`,
`Web Scale?`,
`Erlang`,
`a non-ironic BSOD`,
`ntpdate`,
`Systemd`,
`12 factor application`,
`Fail early, fail often`,
`Regex`,
`A violation of the most basic engineering principles.`,
`The BOFH`,
`A water buffalo`,
`a routing loop`,
`a queue with no consumers`,
`Bitcoin mining`,
`A firewall full of holes`,
`An uncontrollable deluge of emails`,
`I heard about it on hacker news`,
`Ycombinator`,
`a jailbroken iPad`,
`Fuck it, we'll do it live!`,
`Vagrant`,
`Nokogiri Gem`,
`Docker`,
`a "MRW" animated gif`,
`$HOME/.gem`,
`a posting on Craigslist "internet engineers" jobs forum`,
`ssh in a for loop`,
`a cold cup of coffee`,
`Destroying your tools with your tools`,
`UTF-9`,
`a dozen vendor t-shirts`,
`unlimited data plan`,
`UTF-7`,
`out-of-band access`,
`sudo rm -rf /`,
`kill -9`,
`a series of tiny shellscripts`,
`Dogecoin`,
`Kernel panic`,
`Hugops!`,
`Lolcats`,
`Culture`,
`Percussive maintenance`,
`IE 7 Support`,
`Hangops`,
`Unix philosophy`,
`Trying to install MongoDB on AIX 3`,
`A server rack full of crushed dreams`,
`Monads`,
`Silos`,
`Elastic Load Balancers`,
`RFC1178`,
`Full-stack developer`,
`Andrew Clay Shaffer`,
`Jordan Sissel`,
`A new printer.`,
`A potato`,
`Office Space`,
`Git Blame`,
`Developers! Developers! Developers! Developers!`,
`Your account`,
`Single stepping through the kernel`,
`De-linting source code`,
`Significant whitespace`,
`@beerops`,
`A series of tubes`,
`secret sauce`,
`# What is this used for?`,
`Regular Expressions`,
`# FIXME: For now, just don't validate`,
`ASAP`,
`Nagios`,
`The Goddamn CDN`,
`Authentication and authorization`,
`A cluster of applications on a cluster of servers`,
`Beating the server into submission with your bare hands.`,
`Read-only Fridays`,
`r/sysadmin`,
`Distributed Computing`,
`Sprint Planning`,
`Merge Conflicts`,
`# we *LIE* about what happened and return a "success"`,
`Unplugging a server and waiting to see who complains`,
`THE MAGMA PEOPLE ARE WAITING FOR OUR MISTAKES.`,
`a tiny ounce of knowledge`,
`Too big to fail`,
`NoQA Movement`,
`A few instances`,
`operations hipster`,
`Cowboy developer`,
`cubism farm`,
`HipChat`,
`An IRC bot written entirely in sed`,
`works for me`,
`a torrent of Torrenters torrenting`,
`COBOL`,
`in b4 FIRST`,
`Donald Knuth`,
`Rebooting All The Things`,
`Running Openstack in Production`,
`the Berkshelf way`,
`DNS`,
`SIGHUP`,
`Animated GIF`,
`PC LOAD LETTER`,
`Automate`,
`Delightful`,
`Cache`,
`Proxy`,
`an online book seller`,
`Dust Bunnies`,
`Pete Cheslock`,
`Networking`,
`A sad log with a mustache`,
`Blue Screen Of Death`,
`ISO 8601`,
`Daniel J. Bernstein`,
`Linus Torvalds`,
`Broadcom chipset`,
`Moe`,
`That XKCD comic about sysadmins`,
`iso 8859`,
`RFC 1149`,
`A pimply faced youth with nothing to lose`,
`Theo de Raadt yelling at newbs`,
`Hate driven development`,
`Lotus123`,
`IPSec`,
`Hackathons`,
`GNU/Linux`,
`ZeroVM`,
`Stringing cloudtobutt.pl into postfix.`,
`ZeroMQ over SSH`,
`SQLite`,
`LevelDB`,
`Leap second bug`,
`The fucking JVM`,
`continuous deployment`,
`Tor`,
`bash`,
`numactl`,
`zsh`,
`Standing around outside on the streets of SOMA with an overheating laptop drunk while fixing your god damn Saturday night deployment.`,
`Vegan friendly init scripts.`,
`Committing from the bar.`,
`Servers that follow daylight savings time.`,
`Rolling Grubhub into the build failed script.`,
`command line options`,
`Temporary hotfixes`,
`jsLinux`,
`SIGKILL`,
`Your private browsing history`,
`Wearing protection during peer programing.`,
`top`,
`Arguing over the internet.`,
`year 2038`,
`dd`,
`pdisk`,
`rsync`,
`CFLAGS`,
`cowsay`,
`profanity in the git log`,
`Gentoo`,
`The CEO`,
`Ping Pong`,
`Dennis Ritchie`,
`PAM Happy Hour`,
`Complex systems usually operate in failure mode.`,
`FAT32`,
`winsock`,
`fork() on Windows`,
`runlists`,
`sudo`,
`echo shell_exec("sudo ./smbkill ".escapeshellcmd($_GET['kill'])." 2>&1");`,
`kill -9 -1`,
`curl 4chan | sudo sh`,
`HTML9 Responsive Boilerstrap JS`,
`Neckbeards`,
`A Certified SCRUM Master`,
`Bus error`,
`git reset --hard origin/master`,
`Forcing push to master`,
`Paxos`,
`LogFiles\W3SVC1`,
`A German installation of Windows NT4`,
`curl | sh -c`,
`OpenLDAP`,
`Spot Instances`,
`Those ksh scripts`,
`/cgi-bin/php5`,
`A $60 QNAP and some positive thinking`,
`raspberryPI`,
`Windows ME`,
`@echo off`,
`Active Directory`,
`conflict minerals`,
`continuous incineration`,
`The gentle sound of weeping drifting from the server room`,
`eventual consistency`,
`Microsoft® Azure`,
`Pinging the broadcast address`,
`That moment when you realize CTRL-Z cannot save you`,
`127.0.0.1`,
`Ethernet`,
`IPv6`,
`Re-writing deployment scripts at 2 AM`,
`Piping /var/log/messages to Twitter`,
`A pseudorandom number generator`,
`An outage window`,
`Sentinel System Driver`,
`fpm`,
`catastrophic cancellation`,
`termcap`,
`f00d`,
`one giant SPOF`,
`Richard Stallman's Neckbeard`,
`phpMyAdmin`,
`Righteous Anger`,
`/etc/hosts`,
`CEOs with root access`,
`Automagic Metaprogramming`,
`Re-implementing TCP over UDP`,
`Segfault`,
`#define BEGIN  {`,
`Microsoft Access over a WAN`,
`git submodules`,
`Haskell`,
`Functional Reactive`,
`Paxos`,
`memegen`,
`Flynn`,
`eventual persistence`,
`Jenkins`,
`Bingo Balls`,
`Mechanically Recovered Turkey`,
`ChatOps`,
`Scala`,
`WONTFIX`,
`Trello board`,
`mechanically recovered data`,
`Friday afternoon deployment`,
`YoloDB`,
`Piping random scripts from the internet into bash`,
`post-mortems`,
`Github selfies`,
`Production deployments that depend on GitHub`,
`RFC 2324`,
`Your code featured on The Daily WTF.`,
`optimistic transactions`,
`Webscale`,
`Cats`,
`Ponies`,
`Using Brain Fuck in production`,
`Picking the best color to paint your bike shed`,
`Server cages`,
`Copy-on-write`,
`deduplication`,
`LART`,
`BOFH`,
`Program Management`,
`Product Managers`,
`The Ballmer Peak`,
`0xDEADBEEF`,
`A coked-up tech recruiter`,
`A contractor that tells you it was a real learning experience`,
`RTFM`,
`A 1996 Java applet`,
`A virtual machine running a virtual machine until it brings on the Singularity`,
`Ops doing dev = technical debt`,
`#And right here, we'd like a miracle.`,
`Sparkly Devops Princess`,
`Patrick Debois`,
`git merge --force`,
`A series of tubes`,
`A literal cluster fuck`,
`The library that imports all other libraries`,
`The tech lead's shitty pet project`,
`An entirely commented out file`,
`A constructor for RandomThing`,
`Circular imports`,
`A pull request with a winking smiley ;)`,
`Syntactic sugar coma`,
`Former employees who still have admin access to live production servers`,
`The ib_logfiles`,
`The mysql client`,
`Paul Graham`,
`The much neglected IPv5`,
`cron jobs that edit cron jobs`,
`Snail scale`,
`Testing positive for mongonucleosis`,
`PEBKAC`,
`ReiserFS`,
`/dev/null`,
`Little Bobby Tables`,
`Solar flares`,
`Global warming`,
`Short Stroking`,
`Reticulating Splines`,
`RAID 3 SSD cluster`,
`Re-implementing TCP over TCP`,
`Mixed endianness`,
`OAuth`,
`traceroute`,
`rockstar`,
`packet loss`,
`smokeping`,
`losing the root password`,
`Works on my machine!`,
`malloc`,
`buffer overflow`,
`StackOverflow is offline?!`,
`server logs`,
`Penetration test`,
`Deploying on a Friday afternoon`,
`Quipu`,
`too many authorization failures`,
`two single quotes`,
`kremvax`,
`the unix epoch`,
`0-day exploits`,
`tribal knowledge`,
`puppet`,
`RHEL4`,
`DevOps Reactions`,
`syntax error`,
`killall -9`,
`pre caffeine typos`,
`banana pi`,
`RAID 0`,
`PIP`,
`PyPi`,
`Synergy`,
`dev`,
`Java`,
`geometric distances`,
`Indian Ocean`,
`Out of bounds exception`,
`rm -rf /`,
`hunter2`,
`GCHQ`,
`NSA FOIA request`,
`wat`,
`kanban`,
`Halt and Catch Fire`,
`Ansible`,
`Template out`,
`bzero`,
`sendmail`,
`bare metal`,
`Slackware`,
`Bazaar`,
`runit`,
`Home-grown monitoring solution`,
`Virident`,
`v`,
`Arch linux in production`,
`AUR`,
`Btrfs on a 2.6 kernel in production`,
`Actually reading the manual`,
`telnetd on the payment tier`,
`The Hungary Games`,
`the GIL`,
`Solaris`,
`SmartOS`,
`Joyent`,
`Big-endian x86`,
`Uncyclopedia.org`,
`Spongebob Squarepants`,
`Flux Capacitor`,
`Toaster on Wheels`,
`The previous developer`,
`Debian experimental in production`,
`10 years since last update`,
`HAL`,
`Testing in production`,
`The Gang of Four becoming a real gang`,
`Shoving the code down the compilers throat with catch statements`,
`Legacy Code that you're terrified of deleting`,
`That one goddamn line`,
`HTML5 vs Flash`,
`Sudo: make me a sandwich`,
`Java's Syntax`,
`The Travelling Salesman Problem`,
`Subjective C`,
`Ubuntu? I have to learn Ubuntu?`,
`Dell custumer support`,
`The Genius Bar`,
`That Goddamn Paperclip`,
`Laziness, impatience, and hubris`,
`A deleted StackOverflow post`,
`All our code becoming self-documenting because I declared it so`,
`VBScript, the future of software!`,
`The waterfall model`,
`NaN`,
`undefined`,
`An empty int`,
`Continous Testing`,
`Service Virtualization`,
`Test Automation`,
`Writing a Perl script to deploy Puppet Enterprise`,
`The OOM Killer`,
`$lastjob`,
`segfault`,
`$i++`,
`tabs not spaces`,
`spaces not tabs`,
`Spaces and tabs in the same file`,
`iptables`,
`Fedora Core 9`,
`\LaTeX{}`,
`NumPy`,
`An unmaintained man-page`,
`An old Gentoo installation`,
`TeX`,
`null-pointer`,
`Delphi code from the 1990's`,
`Turning it off and on again`,
`A PHP script comprised of shell_exec()'s`,
`A PHP script comprised of exec($_REQUEST['cmd'])`,
`Computer Science III`,
`Multiple measurement systems`,
`Date formats other than yyyy-mm-dd`,
`12 hour clocks`,
`Clocks in a timezone other than UTC`,
`Machines not running NTP`,
`Using Fahrenheit instead of Celsius`,
`Classic Vi`,
`Mesos`,
`Diva designer`,
`sudo chmod -R 777 /`,
`Concurrent Javascript`,
`NaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaN Batman!`,
`Nazi Zombies!!!`,
`Netscape Navigator`,
`Mosaic`,
`Adobe`,
`Microsoft`,
`Apple`,
`Samsung`,
`A new ultrabook`,
`Binaries`,
`Scope Creep`,
`GitHub`,
`A Monad`,
`Silk Road`,
`--enable-h8`,
`--omg-optimized`,
`--funroll-loops`,
`--disable-instructions`,
`An old Solaris developer`,
`This webpage is not available`,
`Dan Kaminsky`,
`65,536`,
`Being marked CLOSED WONTFIX`,
`A datacenter migration`,
`Loading the servers in the back of a shady Canadian's truck`,
`The business acumen of the Mormon Church`,
`High Latency`,
`sudo !!`,
`Defcon`,
`The training budget`,
`SUID root`,
`regex golf`,
`StackOverflow is offline?!`,
`A Monoid`,
`Slashdot`,
`quantum encryption`,
`JIRA Jr!`,
`rm -rf Russian roulette`,
`errors which disappear in debug builds`,
`javascript webservers`,
`sysadmins sneaking Minecraft on the production server`,
`reporting bugs on IRC`,
`Emacs keyboard shortcuts`,
`DevOps podcasts`,
`Hamachi for VPN`,
`debugging Genetically Programmed code`,
`Exchanging childhood memories for 160GiB of storage`,
`Saint IGNUcius`,
`--force`,
`gem native extensions`,
`anti-affinity`,
`multi factor authentication`,
`Python is the new Basic`,
`YAML`,
`Cloud-agnostic`,
`Borland StarTeam`,
`Paralax!`,
`A Python implementation that's basically just a whole bunch of C Preprocessor macros`,
`Idempotence`,
`Chef-client running on OS/2 Warp`,
`@SwiftOnSecurity`,
`Adam Jacob's guitar`,
`PowerShell`,
`Clock skew`,
`A good scotch collection at your desk.`,
`A 1:1 that goes straight to the bar.`,
`A 16 hour incident bridge.`,
`Something said by a NetEng that you didn't understand.`,
`An obscure stack trace`,
`An app with no logging`,
`Steering the Titanic with a popsicle stick`,
`A peer that doesn't believe in peer review`,
`Angular js`,
`A former MENSA member`,
`Being acquired by Oracle`,
`More bloat than GNU code`,
`Emacs pinky problems`,
`Arguing over Java or C#`,
`Best Practices`,
`Programming drunk`,
`Custom Nagios scripts`,
`ITIL`,
`branded hoodies`,
`angel investors`,
`series B funding`,
`A noose made out of cat 5 cable`,
`A kernel hacker's beard`,
`The reaping of child processes`,
`nginx`,
`the outsourced IT department`,
`a NSFW MOTD file`,
`ASCII art`,
`bugzilla`,
`boto`,
`malicious code`,
`The return of the Y2K bug`,
`A highly sophisticated regular expression`,
`A mint-in-box AOL trial CD`,
`log aggregation`,
`The OWASP Top 10`,
`Water-scrum-fall`,
`Yet another attempt at re-writing Nagios`,
`infinite loops`,
`bareword variables`,
`rubocop`,
`A project of Stuxnet-level complexity`,
`Postgis`,
`Terraform`,
`AWK`,
`Greybeards`,
`Database antipatterns`,
`Cat5 'o 9 tails`,
`USB Type-C`,
`Just plain text`,
`HTTP 418: I'm a teapot`,
`haveToMakeMyOwnArrayIsEmptyMethodBecauseCrappyJavaDoesNotHaveIt()`,
`A client with no servers.`,
`Rereading code of last night`,
`Debugging 500 lines of code per method. Average.`,
`localhost`,
`It doesn't happen on my machine`,
`Unit testing randomization`,
`Dropping tables on a Friday`,
`Literally driving development`,
`while(true)`,
`Using a switch for a boolean`,
`ENUM('Y','N');`,
`Mac OS X`,
`Replacing all dev machines with Raspberry Pis`,
`Redirecting www to dev`,
`The Cloud`,
`1337`,
`Minorities in tech`,
`Another Wordpress vulnerability`,
`A Raspberry Pi botnet`,
`DDoSing 127.0.0.1`,
`Low Orbit Ion Cannon`,
`Script kiddies`,
`Hack Forums`,
`/r/talesfromtechsupport`,
`@sadserver`,
`Little Bobby Tables`,
`Downtime`,
`Unixbeards`,
`Excessively long variable names`,
`A parent killing its children`,
`Zombie processes`,
`Commenting every line of code`,
`DEFCON`,
`Richard Stallman`,
`Emojis as identifiers`,
`Trolling the sysadmins`,
`Running Java 6`,
`UNDO UNDO UNDO`,
`Hypertext Coffee Pot Control Protocol`,
`IP Over Avian Carriers`,
`SONET to Sonnet Translation`,
`IP Over Avian Carriers with QoS`,
`SCCS`,
`Infinite Monkey Protocol Suite`,
`National Security Letter`,
`Hyper Text Coffee Pot Control Protocol for Tea Efflux Appliances (HTCPCP-TEA)`,
`NSA (No Secrecy Afforded) Certificate Extension`,
`Scenic Routing for IPv6`,
`Really Explicit Congestion Notification (RECN)`,
`Internet Explorer`,
`Silk Road`,
`The Tor Network`,
`sudo rm -rf /`,
`COBOL`,
`/dev/random`,
`Windows ME`,
`Windows for Workgroups`,
`M-x dwim`,
`===== operator`,
`kibo`,
`Elvish`,
`Klingon`,
`Na'vi`,
`XSLT`,
`A blue box`,
`APL`,
`Snobol`,
`Bogosort`,
`The Jargon File`,
`AI-complete`,
`BCPL`,
`?= operator`,
`12 hamsters`,
`Selenium`,
`A server with no client`,
`Trusting User Input`,
`Guru Meditation`,
`Unexpected T_PAAMAYIM_NEKUDOTAYIM`,
`402: Payment required`,
`Treating warnings as errors`,
`Turning up to work still drunk from yesterday`,
`Private members`,
`EgoDB`,
`LISP`,
`r/talesfromtechsupport`,
`git push --force`,
`A pi stack`,
`PBKAC`,
`Reddit`,
`A poorly abbreviated function name`,
`#nosemver`,
`The .sucks Domain`,
`The <blink> tag`,
`The <marquee> tag`,
`CTRL - C! CTRL - C! CTRL - C!`,
`Internet Of Things`,
`Arduino Hacks`,
`Founders`,
`Early Engineers`,
`cat /etc/passwd`,
`Code Golf`,
`Stack Overflow`,
`Cassandra`,
`BizDev`,
`Cult of the Dead Cow`,
`mv / /dev/null`,
`rm -f /usr/bin/sudo; rm -f /bin/su`,
`an infinite whiteboard`,
`the mythical man-month`,
`HHCdT`,
`Allow s3:*`,
`Embedded IAM roles`,
`Rebasing Master`,
`Ada Lovelace`,
`//wait what is this supposed to do`,
`Windows`,
`Patch Tuesday`,
`GNU/Windows`,
`{{REASONS}}`,
`Stack Smashing`,
`The 8th Layer of the OSI Model`,
`The 9th Layer of the OSI Model`,
`:Q :q :w :q :q!`,
`Atlassian Products`,
`Kubernetes`,
`Moby`,		
		},
	}

	AddPack(pack)
}
