package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "yo-mama",
		Description: "Yo Mama Cards",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `%s + %s = %s.`},
			&PromptCard{Prompt: `Yo mama's so fat, %s.`},
			&PromptCard{Prompt: `Yo mama's so stupid, %s.`},
			&PromptCard{Prompt: `Yo mama's so ugly, %s.`},
			&PromptCard{Prompt: `Yo mama's so old, %s.`},
			&PromptCard{Prompt: `Yo mama's so poor, %s.`},
			&PromptCard{Prompt: `Yo mama's so depressing, %s.`},
			&PromptCard{Prompt: `Yo mama's so short, %s.`},
			&PromptCard{Prompt: `Yo mama so big, %s.`},
			&PromptCard{Prompt: `Yo mama so scary, %s.`},
			&PromptCard{Prompt: `Yo mama's so nasty, %s.`},
			&PromptCard{Prompt: `Yo mama so dumb, %s.`},
		},
		Responses: []ResponseCard{
			`"IDFK I hate this game"`,
			`"when she fell, I didn't laugh, but the sidewalk cracked"`,
			`"when she skips a meal, the stock market drops"`,
			`"it took me two buses and a train to get to her good side"`,
			`"when she goes camping, the bears hide their food"`,
			`"if she buys a fur coat, a whole species will become extinct"`,
			`"she stepped on a scale and it said: "To be continued"`,
			`"I swerved to miss her in my car and ran out of gas"`,
			`"when she wears high heels, she strikes oil"`,
			`"when she sits around the house, she SITS AROUND the house"`,
			`"her car has stretch marks"`,
			`"she can't even jump to a conclusion"`,
			`"her blood type is Ragu"`,
			`"if she was a Star Wars character, her name would be Admiral Snackbar"`,
			`"she brought a spoon to the Super Bowl"`,
			`"she stared at a cup of orange juice for 12 hours because it said "concentrate"`,
			`"when they said it was chilly outside, she grabbed a bowl"`,
			`"she put lipstick on her forehead to make up her mind"`,
			`"when they said, "Order in the court," she asked for fries and a shake"`,
			`"she thought a quarterback was a refund"`,
			`"she got hit by a parked car"`,
			`"when I told her that she lost her mind, she went looking for it"`,
			`"when thieves broke into her house and stole the TV, she chased after them shouting "Wait, you forgot the remote!"`,
			`"she went to the dentist to get a Bluetooth"`,
			`"she took a ruler to bed to see how long she slept"`,
			`"she got locked in the grocery store and starved to death"`,
			`"when I said, "Drinks on the house," she got a ladder"`,
			`"it takes her two hours to watch 60 Minutes"`,
			`"she put airbags on her computer in case it crashed"`,
			`"she threw a boomerang and it refused to come back"`,
			`"her social security number is one"`,
			`"she made a blind kid cry"`,
			`"her portraits hang themselves"`,
			`"she walked out of a museum and the alarm went off"`,
			`"when she was little, she had to trick-or-treat by phone"`,
			`"her birth certificate is an apology letter"`,
			`"she looked out the window and was arrested for mooning"`,
			`"the ducks throw bread at her"`,
			`"she chases the garbage truck with a grocery list"`,
			`"blues singers come to visit her when they've got writer's block"`,
			`"you can see her feet on her driver's license"`,
			`"she can't even afford to pay attention"`,
			`"her belt size is 'equator'"`,
			`"she went to see Santa and he told her to get back to work"`,
			`"the government moved Halloween to her birthday"`,
			`"they used to call them jumpolines 'til yo mama bounced on one"`,
			`"Nigerian princes wire her money"`,
			`"she went to the eye doctor to get an iPhone"`,
			`"she stuck her nose out the window and let the wind blow it"`,
		},
	}

	AddPack(pack)
}
